// @ts-check

import { createHash } from "node:crypto";
import { existsSync, lstatSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import { ownershipError } from "../errors.mjs";
export const MANAGED_MARKER = "Generated by Tama Kit";

/** @typedef {import("../types.mjs").FileOperation} FileOperation */
/** @typedef {import("../types.mjs").FileOperationOptions} FileOperationOptions */

/** @param {string} content */
export function contentDigest(content) {
  return `sha256:${createHash("sha256").update(content).digest("hex")}`;
}

/** Inspect dangling links as well as existing paths; never follow a symlink ancestor.
 * @param {string} filename
 * @returns {import("node:fs").Stats | null}
 */
export function inspectRegularFile(filename) {
  const absolute = resolve(filename);
  let current = absolute;
  let result = null;
  while (true) {
    let metadata;
    try {
      metadata = lstatSync(current);
    } catch (error) {
      if (!(error instanceof Error) || !("code" in error) || error.code !== "ENOENT") throw error;
    }
    if (metadata) {
      if (
        metadata.isSymbolicLink() ||
        (current === absolute ? !metadata.isFile() : !metadata.isDirectory())
      ) {
        throw ownershipError(
          "generation destination must be a regular file with real directory ancestors",
          {
            path: filename,
          },
        );
      }
      if (current === absolute) result = metadata;
    }
    const parent = dirname(current);
    if (parent === current) break;
    current = parent;
  }
  return result;
}

/** Markers identify provenance only. This planner never updates an existing file.
 * @param {string} filename
 * @param {string} content
 * @param {{sensitive?: boolean, mode?: number}} [options]
 * @returns {import("../domain/generation.mjs").GenerationOperation}
 */
export function generationOperationForContent(filename, content, { sensitive = false, mode } = {}) {
  const metadata = inspectRegularFile(filename);
  if (metadata === null) {
    return {
      action: "create",
      path: filename,
      content,
      owner: "user",
      sensitive,
      mode,
      beforeDigest: null,
      afterDigest: contentDigest(content),
      reason: "new generation destination",
    };
  }
  const identical = readFileSync(filename, "utf8") === content;
  return {
    action: identical ? "preserve" : "conflict",
    path: filename,
    sensitive,
    reason: identical
      ? "existing content is identical; preserve permissions"
      : "destination already contains different project-owned content",
  };
}

/** @param {string} content */
export function hasManagedMarker(content) {
  const firstLine = content.split(/\r?\n/u, 1)[0];
  return (
    firstLine.startsWith(`# ${MANAGED_MARKER}`) || firstLine.startsWith(`<!-- ${MANAGED_MARKER}`)
  );
}

/**
 * @param {string} filename
 * @param {string} content
 * @param {FileOperationOptions} [options]
 * @returns {FileOperation}
 */
export function operationForContent(
  filename,
  content,
  { owner = "tama-kit", sensitive = false, mode, allowUnmanagedUpdate = false } = {},
) {
  if (!existsSync(filename)) {
    return {
      action: "create",
      path: filename,
      content,
      owner,
      sensitive,
      mode,
      beforeDigest: null,
      afterDigest: contentDigest(content),
      reason: "file does not exist",
    };
  }
  const fileStats = lstatSync(filename);
  if (fileStats.isSymbolicLink()) {
    throw ownershipError(`refusing to update a symbolic link: ${filename}`, { path: filename });
  }

  const before = readFileSync(filename, "utf8");
  const beforeDigest = contentDigest(before);
  const afterDigest = contentDigest(content);
  if (before === content) {
    if (mode !== undefined && (fileStats.mode & 0o777) !== mode) {
      return {
        action: "update",
        path: filename,
        content,
        owner,
        sensitive,
        mode,
        beforeDigest,
        afterDigest,
        reason: "file permissions differ",
      };
    }
    return {
      action: "unchanged",
      path: filename,
      owner,
      sensitive,
      mode,
      beforeDigest,
      afterDigest,
      reason: "content and permissions match",
    };
  }
  if (!allowUnmanagedUpdate && !hasManagedMarker(before)) {
    throw ownershipError(`refusing to overwrite an unmanaged file: ${filename}`, {
      path: filename,
    });
  }
  return {
    action: "update",
    path: filename,
    content,
    owner,
    sensitive,
    mode,
    beforeDigest,
    afterDigest,
    reason: "managed content differs",
  };
}
