// @ts-check

import { readFileSync } from "node:fs";
import { isGenerationPath, mapping, parseGenerationReceipt } from "../domain/generation.mjs";
import { ownershipError } from "../errors.mjs";
import { inspectRegularFile } from "../shared/files.mjs";

/**
 * Recognize v1 history without loading canonical topology or comparing project
 * files to old hashes. A legacy inventory never authorizes resume or recreation.
 * @param {unknown} value
 * @returns {import("../domain/generation.mjs").GenerationEvidence}
 */
export function adaptLegacyGenerationManifest(value) {
  const record = mapping(value);
  const files = mapping(record?.managedFiles);
  if (
    record?.schemaVersion !== 1 ||
    record.generator !== "Generated by Tama Kit" ||
    !files ||
    Object.entries(files).some(
      ([path, digest]) =>
        !isGenerationPath(path) ||
        typeof digest !== "string" ||
        !/^sha256:[0-9a-f]{64}$/u.test(digest),
    )
  ) {
    throw ownershipError(
      "invalid legacy generation metadata; inspect current configuration explicitly",
    );
  }
  return { kind: "legacy", schemaVersion: 1 };
}

/**
 * Read only. Does not inspect historical destinations or convert metadata on disk.
 * @param {string} filename Explicit selected receipt/legacy manifest path.
 * @returns {import("../domain/generation.mjs").GenerationEvidence}
 */
export function readGenerationEvidence(filename) {
  if (inspectRegularFile(filename) === null) return { kind: "absent" };
  let value;
  try {
    value = JSON.parse(readFileSync(filename, "utf8"));
  } catch {
    // JSON parser messages can include private file contents.
    throw ownershipError(
      "cannot parse generation metadata; inspect current configuration explicitly",
      {
        path: filename,
      },
    );
  }
  if (mapping(value)?.schemaVersion === 1) return adaptLegacyGenerationManifest(value);
  return { kind: "receipt", receipt: parseGenerationReceipt(value) };
}
