// @ts-check

import { existsSync, lstatSync, readFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

import { ownershipError } from "../errors.mjs";
import { contentDigest, operationForContent } from "./files.mjs";

/** @typedef {import("../types.mjs").FileOperation} FileOperation */
/** @typedef {import("../types.mjs").FileOperationOptions} FileOperationOptions */

const MANIFEST_SCHEMA_VERSION = 1;
const MANIFEST_GENERATOR = "Generated by Tama Kit";

/**
 * @param {string} tamaDirectory
 * @returns {import("../types.mjs").AgentSkillMode | null}
 */
export function readAgentSkillMode(tamaDirectory) {
  const manifestPath = join(tamaDirectory, ".tama-kit.json");
  if (!existsSync(manifestPath) || lstatSync(manifestPath).isSymbolicLink()) {
    return null;
  }
  try {
    const manifest = mapping(JSON.parse(readFileSync(manifestPath, "utf8")));
    return manifest?.agentSkills === "local" || manifest?.agentSkills === "manual"
      ? manifest.agentSkills
      : null;
  } catch {
    return null;
  }
}

/** @param {unknown} value */
function mapping(value) {
  return value && typeof value === "object" && !Array.isArray(value)
    ? /** @type {Record<string, unknown>} */ (value)
    : null;
}

/** @param {string} root @param {string} filename */
function projectRelativePath(root, filename) {
  const path = relative(root, filename).split(sep).join("/");
  if (path === ".." || path.startsWith("../") || path === "") {
    throw ownershipError(`managed file must be inside the project root: ${filename}`, {
      path: filename,
    });
  }
  return path;
}

/** @param {string} root @param {string} filename */
function safeManagedPath(root, filename) {
  const path = projectRelativePath(root, filename);
  const ancestors = path.split("/").slice(0, -1);
  let current = root;

  for (const ancestor of ancestors) {
    current = join(current, ancestor);
    let metadata;
    try {
      metadata = lstatSync(current);
    } catch (error) {
      const code = error instanceof Error && "code" in error ? error.code : undefined;
      if (code === "ENOENT") {
        break;
      }
      const message = error instanceof Error ? error.message : String(error);
      throw ownershipError(`cannot inspect managed file ancestor ${current}: ${message}`, {
        path: filename,
        ancestorPath: current,
      });
    }
    if (metadata.isSymbolicLink()) {
      throw ownershipError(
        `refusing to manage a file through a symbolic-link directory: ${current}`,
        {
          path: filename,
          ancestorPath: current,
        },
      );
    }
    if (!metadata.isDirectory()) {
      throw ownershipError(`managed file ancestor is not a directory: ${current}`, {
        path: filename,
        ancestorPath: current,
      });
    }
  }

  return path;
}

/**
 * @param {string} root
 * @param {string} tamaDirectory
 * @param {import("../types.mjs").AgentSkillMode} skillMode
 */
export function createManagedFilePlanner(root, tamaDirectory, skillMode) {
  const manifestPath = join(tamaDirectory, ".tama-kit.json");
  /** @type {Map<string, string>} */
  const recorded = new Map();

  if (existsSync(manifestPath)) {
    if (lstatSync(manifestPath).isSymbolicLink()) {
      throw ownershipError(`refusing to use a symbolic-link Tama Kit manifest: ${manifestPath}`, {
        path: manifestPath,
      });
    }
    let manifest;
    try {
      manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw ownershipError(`cannot read Tama Kit manifest ${manifestPath}: ${message}`, {
        path: manifestPath,
      });
    }
    const rootValue = mapping(manifest);
    const files = mapping(rootValue?.managedFiles);
    if (
      rootValue?.schemaVersion !== MANIFEST_SCHEMA_VERSION ||
      rootValue.generator !== MANIFEST_GENERATOR ||
      !files
    ) {
      throw ownershipError(`unsupported or unmanaged Tama Kit manifest: ${manifestPath}`, {
        path: manifestPath,
      });
    }
    for (const [path, digest] of Object.entries(files)) {
      if (typeof digest !== "string" || !/^sha256:[0-9a-f]{64}$/u.test(digest)) {
        throw ownershipError(`Tama Kit manifest contains an invalid digest for ${path}`, {
          path: manifestPath,
          managedPath: path,
        });
      }
      const resolved = join(root, path);
      if (projectRelativePath(root, resolved) !== path.split("\\").join("/")) {
        throw ownershipError(`Tama Kit manifest contains an unsafe managed path: ${path}`, {
          path: manifestPath,
          managedPath: path,
        });
      }
      recorded.set(path, digest);
    }
  }

  /** @type {Map<string, string>} */
  const desired = new Map(recorded);
  const planned = new Set();

  /**
   * @param {string} filename
   * @param {string} content
   * @param {FileOperationOptions} [options]
   * @returns {FileOperation}
   */
  function plan(filename, content, options = {}) {
    const path = safeManagedPath(root, filename);
    if (recorded.has(path) && !existsSync(filename)) {
      throw ownershipError(`managed file recorded by Tama Kit is missing: ${filename}`, {
        path: filename,
      });
    }
    planned.add(path);
    const digest = contentDigest(content);
    desired.set(path, digest);

    if (existsSync(filename)) {
      if (lstatSync(filename).isSymbolicLink()) {
        throw ownershipError(`refusing to update a symbolic link: ${filename}`, { path: filename });
      }
      const currentDigest = contentDigest(readFileSync(filename, "utf8"));
      const previousDigest = recorded.get(path);
      if (currentDigest !== digest && currentDigest !== previousDigest) {
        throw ownershipError(`managed file has user-modified content: ${filename}`, {
          path: filename,
          expectedDigest: previousDigest ?? null,
          actualDigest: currentDigest,
        });
      }
    }

    return operationForContent(filename, content, { ...options, allowUnmanagedUpdate: true });
  }

  /** @param {string} filename @param {string[]} knownContents */
  function adoptMarkedFile(filename, knownContents) {
    if (!existsSync(filename)) {
      return;
    }
    safeManagedPath(root, filename);
    if (lstatSync(filename).isSymbolicLink()) {
      throw ownershipError(`refusing to adopt a symbolic link: ${filename}`, { path: filename });
    }
    const content = readFileSync(filename, "utf8");
    const firstLine = content.split(/\r?\n/u, 1)[0];
    if (!firstLine.startsWith("# Generated by Tama Kit")) {
      return;
    }
    const path = projectRelativePath(root, filename);
    const digest = contentDigest(content);
    const previousDigest = recorded.get(path);
    if (previousDigest && previousDigest !== digest) {
      throw ownershipError(`managed file has user-modified content: ${filename}`, {
        path: filename,
        expectedDigest: previousDigest,
        actualDigest: digest,
      });
    }
    if (!previousDigest && !knownContents.some((known) => contentDigest(known) === digest)) {
      throw ownershipError(
        `cannot establish ownership of marked legacy Terraform file: ${filename}`,
        {
          path: filename,
          actualDigest: digest,
        },
      );
    }
    recorded.set(path, digest);
    planned.add(path);
    desired.set(path, digest);
  }

  /** @param {string} filename */
  function isManagedFile(filename) {
    return recorded.has(projectRelativePath(root, filename));
  }

  /** @returns {FileOperation} */
  function manifestOperation() {
    for (const [path, digest] of recorded) {
      if (planned.has(path)) {
        continue;
      }
      const filename = join(root, path);
      safeManagedPath(root, filename);
      if (!existsSync(filename) || lstatSync(filename).isSymbolicLink()) {
        throw ownershipError(
          `managed file recorded by Tama Kit is missing or unsafe: ${filename}`,
          {
            path: filename,
          },
        );
      }
      const actualDigest = contentDigest(readFileSync(filename, "utf8"));
      if (actualDigest !== digest) {
        throw ownershipError(`managed file has user-modified content: ${filename}`, {
          path: filename,
          expectedDigest: digest,
          actualDigest,
        });
      }
    }

    const managedFiles = Object.fromEntries(
      [...desired.entries()].sort(([left], [right]) => left.localeCompare(right, "en")),
    );
    const content = `${JSON.stringify(
      {
        schemaVersion: MANIFEST_SCHEMA_VERSION,
        generator: MANIFEST_GENERATOR,
        agentSkills: skillMode,
        managedFiles,
      },
      null,
      2,
    )}\n`;
    return operationForContent(manifestPath, content, { allowUnmanagedUpdate: true });
  }

  return { plan, adoptMarkedFile, isManagedFile, manifestOperation };
}
