// @ts-check

import { existsSync, lstatSync, readFileSync } from "node:fs";
import { isAbsolute, join, relative, sep } from "node:path";

import { ownershipError } from "../errors.mjs";
import { contentDigest, operationForContent } from "./files.mjs";

/** @typedef {import("../types.mjs").FileOperation} FileOperation */
/** @typedef {import("../types.mjs").FileOperationOptions} FileOperationOptions */
/** @typedef {import("../types.mjs").PersistedMcpAppProvider} PersistedMcpAppProvider */

const MANIFEST_SCHEMA_VERSION = 1;
const MANIFEST_GENERATOR = "Generated by Tama Kit";
const MCP_APP_CONTRACT_SOURCES = Object.freeze(["contract", "conventional"]);
const MCP_APP_LOADING_STATES = Object.freeze(["verified", "unverified"]);
const MCP_APP_LOADING_MECHANISMS = Object.freeze(["direnv", "compose-env-file"]);

/**
 * Project-local contracts move with the project, so their manifest path is
 * relative to the project root. Explicit contracts outside the project keep
 * their absolute path because there is no portable project-relative target.
 *
 * @param {string} root
 * @param {string | null} path
 * @returns {string | null}
 */
function portableContractPath(root, path) {
  if (path === null || !isAbsolute(path)) {
    return path;
  }
  const local = relative(root, path);
  if (local === "" || isAbsolute(local) || local === ".." || local.startsWith(`..${sep}`)) {
    return path;
  }
  return local.split(sep).join("/");
}

/**
 * Parses the persisted MCP App provider block. An absent block yields null;
 * a present but malformed block fails closed because the manifest is Tama
 * Kit owned and a silent identity loss would rename the provider fragment.
 *
 * @param {unknown} value
 * @param {string} manifestPath
 * @returns {PersistedMcpAppProvider | null}
 */
function parsePersistedProvider(value, manifestPath) {
  const provider = mapping(value);
  if (provider === null) {
    return null;
  }
  if (
    typeof provider.name !== "string" ||
    typeof provider.environmentPrefix !== "string" ||
    typeof provider.environmentFile !== "string" ||
    !MCP_APP_CONTRACT_SOURCES.includes(/** @type {string} */ (provider.contractSource)) ||
    (provider.contractPath !== null && typeof provider.contractPath !== "string") ||
    !MCP_APP_LOADING_STATES.includes(/** @type {string} */ (provider.environmentLoading))
  ) {
    throw ownershipError(`Tama Kit manifest contains an invalid mcpAppProvider: ${manifestPath}`, {
      path: manifestPath,
    });
  }
  const loadingMechanism = provider.environmentLoadingMechanism;
  const loadingEvidencePath = provider.environmentLoadingEvidencePath;
  if (
    loadingMechanism !== undefined &&
    loadingMechanism !== null &&
    !MCP_APP_LOADING_MECHANISMS.includes(/** @type {string} */ (loadingMechanism))
  ) {
    throw ownershipError(
      `Tama Kit manifest contains an invalid MCP App environment loading mechanism: ${manifestPath}`,
      { path: manifestPath },
    );
  }
  if (
    loadingEvidencePath !== undefined &&
    loadingEvidencePath !== null &&
    (typeof loadingEvidencePath !== "string" || loadingEvidencePath.length === 0)
  ) {
    throw ownershipError(
      `Tama Kit manifest contains invalid MCP App environment loading evidence: ${manifestPath}`,
      { path: manifestPath },
    );
  }
  if (
    provider.environmentLoading === "unverified" &&
    (loadingMechanism != null || loadingEvidencePath != null)
  ) {
    throw ownershipError(
      `Tama Kit manifest unverified MCP App environment loading cannot claim evidence: ${manifestPath}`,
      { path: manifestPath },
    );
  }
  if (
    (loadingMechanism === null) !== (loadingEvidencePath === null) ||
    (loadingMechanism === undefined) !== (loadingEvidencePath === undefined)
  ) {
    throw ownershipError(
      `Tama Kit manifest MCP App environment loading evidence is incomplete: ${manifestPath}`,
      { path: manifestPath },
    );
  }
  const bindings = mapping(provider.bindings);
  if (bindings === null) {
    throw ownershipError(`Tama Kit manifest mcpAppProvider is missing bindings: ${manifestPath}`, {
      path: manifestPath,
    });
  }
  for (const [role, variable] of Object.entries(bindings)) {
    if (typeof variable !== "string" || variable.length === 0) {
      throw ownershipError(
        `Tama Kit manifest mcpAppProvider bindings has an invalid ${role} role: ${manifestPath}`,
        { path: manifestPath },
      );
    }
  }
  const topologyValues = [provider.providerOrigin, provider.tamaOrigin, provider.allowedOrigins];
  const hasTopology = topologyValues.some((value) => value !== undefined);
  if (
    hasTopology &&
    (typeof provider.providerOrigin !== "string" ||
      typeof provider.tamaOrigin !== "string" ||
      !Array.isArray(provider.allowedOrigins) ||
      provider.allowedOrigins.length === 0 ||
      provider.allowedOrigins.length > 32 ||
      provider.allowedOrigins.some((origin) => typeof origin !== "string" || origin.length === 0) ||
      new Set(provider.allowedOrigins).size !== provider.allowedOrigins.length)
  ) {
    throw ownershipError(
      `Tama Kit manifest contains an invalid mcpAppProvider topology: ${manifestPath}`,
      { path: manifestPath },
    );
  }
  const localHttps = provider.localHttps;
  if (localHttps !== undefined) {
    if (!localHttps || typeof localHttps !== "object" || Array.isArray(localHttps)) {
      throw ownershipError(
        `Tama Kit manifest contains an invalid local HTTPS topology: ${manifestPath}`,
        {
          path: manifestPath,
        },
      );
    }
    const topology = /** @type {Record<string, unknown>} */ (localHttps);
    const required = [
      "profile",
      "localDomain",
      "providerHost",
      "tamaHost",
      "providerOrigin",
      "tamaOrigin",
      "providerPort",
      "tamaPort",
      "httpsPort",
      "certificateNames",
      "caddyImage",
      "trustMechanism",
      "allowedOrigins",
    ];
    if (
      required.some((key) => !(key in topology)) ||
      topology.profile !== "mcp-app-local-https" ||
      typeof topology.localDomain !== "string" ||
      typeof topology.providerHost !== "string" ||
      typeof topology.tamaHost !== "string" ||
      typeof topology.providerOrigin !== "string" ||
      typeof topology.tamaOrigin !== "string" ||
      !Number.isInteger(topology.providerPort) ||
      !Number.isInteger(topology.tamaPort) ||
      topology.httpsPort !== 443 ||
      !Array.isArray(topology.certificateNames) ||
      topology.certificateNames.some((name) => typeof name !== "string") ||
      typeof topology.caddyImage !== "string" ||
      typeof topology.trustMechanism !== "string" ||
      !Array.isArray(topology.allowedOrigins) ||
      topology.allowedOrigins.length === 0 ||
      topology.allowedOrigins.length > 32 ||
      topology.allowedOrigins.some((origin) => typeof origin !== "string" || origin.length === 0) ||
      new Set(topology.allowedOrigins).size !== topology.allowedOrigins.length
    ) {
      throw ownershipError(
        `Tama Kit manifest contains an invalid local HTTPS topology: ${manifestPath}`,
        {
          path: manifestPath,
        },
      );
    }
  }
  return {
    identity: {
      name: provider.name,
      environmentPrefix: provider.environmentPrefix,
      environmentFile: provider.environmentFile,
      source: "manifest",
    },
    contractSource: /** @type {"contract" | "conventional"} */ (provider.contractSource),
    contractPath: provider.contractPath === null ? null : provider.contractPath,
    bindings: /** @type {Record<string, string>} */ (bindings),
    environmentLoading: /** @type {"verified" | "unverified"} */ (provider.environmentLoading),
    environmentLoadingMechanism:
      loadingMechanism === "direnv" || loadingMechanism === "compose-env-file"
        ? loadingMechanism
        : null,
    environmentLoadingEvidencePath:
      typeof loadingEvidencePath === "string" ? loadingEvidencePath : null,
    ...(hasTopology
      ? {
          providerOrigin: /** @type {string} */ (provider.providerOrigin),
          tamaOrigin: /** @type {string} */ (provider.tamaOrigin),
          allowedOrigins: /** @type {string[]} */ (provider.allowedOrigins),
        }
      : {}),
    ...(localHttps !== undefined
      ? { localHttps: /** @type {import("../types.mjs").LocalHttpsTopology} */ (localHttps) }
      : {}),
  };
}

/**
 * @param {string} tamaDirectory
 * @returns {PersistedMcpAppProvider | null}
 */
export function readMcpAppProvider(tamaDirectory) {
  const manifestPath = join(tamaDirectory, ".tama-kit.json");
  if (!existsSync(manifestPath) || lstatSync(manifestPath).isSymbolicLink()) {
    return null;
  }
  let manifest;
  try {
    manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw ownershipError(`cannot read Tama Kit manifest ${manifestPath}: ${message}`, {
      path: manifestPath,
    });
  }
  return parsePersistedProvider(mapping(manifest)?.mcpAppProvider, manifestPath);
}

/**
 * @param {string} tamaDirectory
 * @returns {import("../types.mjs").AgentSkillMode | null}
 */
export function readAgentSkillMode(tamaDirectory) {
  const manifestPath = join(tamaDirectory, ".tama-kit.json");
  if (!existsSync(manifestPath) || lstatSync(manifestPath).isSymbolicLink()) {
    return null;
  }
  try {
    const manifest = mapping(JSON.parse(readFileSync(manifestPath, "utf8")));
    return manifest?.agentSkills === "local" || manifest?.agentSkills === "manual"
      ? manifest.agentSkills
      : null;
  } catch {
    return null;
  }
}

/** @param {unknown} value */
function mapping(value) {
  return value && typeof value === "object" && !Array.isArray(value)
    ? /** @type {Record<string, unknown>} */ (value)
    : null;
}

/** @param {string} root @param {string} filename */
function projectRelativePath(root, filename) {
  const path = relative(root, filename).split(sep).join("/");
  if (path === ".." || path.startsWith("../") || path === "") {
    throw ownershipError(`managed file must be inside the project root: ${filename}`, {
      path: filename,
    });
  }
  return path;
}

/** @param {string} root @param {string} filename */
function safeManagedPath(root, filename) {
  const path = projectRelativePath(root, filename);
  const ancestors = path.split("/").slice(0, -1);
  let current = root;

  for (const ancestor of ancestors) {
    current = join(current, ancestor);
    let metadata;
    try {
      metadata = lstatSync(current);
    } catch (error) {
      const code = error instanceof Error && "code" in error ? error.code : undefined;
      if (code === "ENOENT") {
        break;
      }
      const message = error instanceof Error ? error.message : String(error);
      throw ownershipError(`cannot inspect managed file ancestor ${current}: ${message}`, {
        path: filename,
        ancestorPath: current,
      });
    }
    if (metadata.isSymbolicLink()) {
      throw ownershipError(
        `refusing to manage a file through a symbolic-link directory: ${current}`,
        {
          path: filename,
          ancestorPath: current,
        },
      );
    }
    if (!metadata.isDirectory()) {
      throw ownershipError(`managed file ancestor is not a directory: ${current}`, {
        path: filename,
        ancestorPath: current,
      });
    }
  }

  return path;
}

/**
 * @param {string} root
 * @param {string} tamaDirectory
 * @param {import("../types.mjs").AgentSkillMode} skillMode
 * @param {PersistedMcpAppProvider | null} [mcpAppProvider]
 */
export function createManagedFilePlanner(root, tamaDirectory, skillMode, mcpAppProvider = null) {
  const manifestPath = join(tamaDirectory, ".tama-kit.json");
  /** @type {Map<string, string>} */
  const recorded = new Map();
  /** @type {PersistedMcpAppProvider | null} */
  let existingProvider = null;

  if (existsSync(manifestPath)) {
    if (lstatSync(manifestPath).isSymbolicLink()) {
      throw ownershipError(`refusing to use a symbolic-link Tama Kit manifest: ${manifestPath}`, {
        path: manifestPath,
      });
    }
    let manifest;
    try {
      manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw ownershipError(`cannot read Tama Kit manifest ${manifestPath}: ${message}`, {
        path: manifestPath,
      });
    }
    const rootValue = mapping(manifest);
    const files = mapping(rootValue?.managedFiles);
    if (
      rootValue?.schemaVersion !== MANIFEST_SCHEMA_VERSION ||
      rootValue.generator !== MANIFEST_GENERATOR ||
      !files
    ) {
      throw ownershipError(`unsupported or unmanaged Tama Kit manifest: ${manifestPath}`, {
        path: manifestPath,
      });
    }
    existingProvider = parsePersistedProvider(rootValue?.mcpAppProvider, manifestPath);
    for (const [path, digest] of Object.entries(files)) {
      if (typeof digest !== "string" || !/^sha256:[0-9a-f]{64}$/u.test(digest)) {
        throw ownershipError(`Tama Kit manifest contains an invalid digest for ${path}`, {
          path: manifestPath,
          managedPath: path,
        });
      }
      const resolved = join(root, path);
      if (projectRelativePath(root, resolved) !== path.split("\\").join("/")) {
        throw ownershipError(`Tama Kit manifest contains an unsafe managed path: ${path}`, {
          path: manifestPath,
          managedPath: path,
        });
      }
      recorded.set(path, digest);
    }
  }

  /** @type {Map<string, string>} */
  const desired = new Map(recorded);
  const planned = new Set();

  /**
   * @param {string} filename
   * @param {string} content
   * @param {FileOperationOptions} [options]
   * @returns {FileOperation}
   */
  function plan(filename, content, options = {}) {
    const path = safeManagedPath(root, filename);
    if (recorded.has(path) && !existsSync(filename)) {
      throw ownershipError(`managed file recorded by Tama Kit is missing: ${filename}`, {
        path: filename,
      });
    }
    planned.add(path);
    const digest = contentDigest(content);
    desired.set(path, digest);

    if (existsSync(filename)) {
      if (lstatSync(filename).isSymbolicLink()) {
        throw ownershipError(`refusing to update a symbolic link: ${filename}`, { path: filename });
      }
      const currentDigest = contentDigest(readFileSync(filename, "utf8"));
      const previousDigest = recorded.get(path);
      if (currentDigest !== digest && currentDigest !== previousDigest) {
        throw ownershipError(`managed file has user-modified content: ${filename}`, {
          path: filename,
          expectedDigest: previousDigest ?? null,
          actualDigest: currentDigest,
        });
      }
    }

    return operationForContent(filename, content, { ...options, allowUnmanagedUpdate: true });
  }

  /**
   * Plans deletion of an unchanged Tama Kit-managed file. This is used only
   * for explicit migrations where retaining the old secret fragment would
   * leave two provider identities active.
   *
   * @param {string} filename
   * @param {FileOperationOptions} [options]
   * @returns {FileOperation}
   */
  function remove(filename, options = {}) {
    const path = safeManagedPath(root, filename);
    const previousDigest = recorded.get(path);
    if (!previousDigest || !existsSync(filename) || lstatSync(filename).isSymbolicLink()) {
      throw ownershipError(`cannot migrate unmanaged or unsafe file: ${filename}`, {
        path: filename,
      });
    }
    const currentDigest = contentDigest(readFileSync(filename, "utf8"));
    if (currentDigest !== previousDigest) {
      throw ownershipError(`managed file has user-modified content: ${filename}`, {
        path: filename,
        expectedDigest: previousDigest,
        actualDigest: currentDigest,
      });
    }
    planned.add(path);
    desired.delete(path);
    return {
      action: "delete",
      path: filename,
      owner: options.owner ?? "tama-kit",
      sensitive: options.sensitive ?? false,
      ...(options.mode === undefined ? {} : { mode: options.mode }),
      beforeDigest: currentDigest,
      afterDigest: null,
      reason: "remove superseded managed file",
    };
  }

  /** @param {string} filename @param {string[]} knownContents */
  function adoptMarkedFile(filename, knownContents) {
    if (!existsSync(filename)) {
      return;
    }
    safeManagedPath(root, filename);
    if (lstatSync(filename).isSymbolicLink()) {
      throw ownershipError(`refusing to adopt a symbolic link: ${filename}`, { path: filename });
    }
    const content = readFileSync(filename, "utf8");
    const firstLine = content.split(/\r?\n/u, 1)[0];
    if (!firstLine.startsWith("# Generated by Tama Kit")) {
      return;
    }
    const path = projectRelativePath(root, filename);
    const digest = contentDigest(content);
    const previousDigest = recorded.get(path);
    if (previousDigest && previousDigest !== digest) {
      throw ownershipError(`managed file has user-modified content: ${filename}`, {
        path: filename,
        expectedDigest: previousDigest,
        actualDigest: digest,
      });
    }
    if (!previousDigest && !knownContents.some((known) => contentDigest(known) === digest)) {
      throw ownershipError(
        `cannot establish ownership of marked legacy Terraform file: ${filename}`,
        {
          path: filename,
          actualDigest: digest,
        },
      );
    }
    recorded.set(path, digest);
    planned.add(path);
    desired.set(path, digest);
  }

  /** @param {string} filename */
  function isManagedFile(filename) {
    return recorded.has(projectRelativePath(root, filename));
  }

  /** @returns {FileOperation} */
  function manifestOperation() {
    for (const [path, digest] of recorded) {
      if (planned.has(path)) {
        continue;
      }
      const filename = join(root, path);
      safeManagedPath(root, filename);
      if (!existsSync(filename) || lstatSync(filename).isSymbolicLink()) {
        throw ownershipError(
          `managed file recorded by Tama Kit is missing or unsafe: ${filename}`,
          {
            path: filename,
          },
        );
      }
      const actualDigest = contentDigest(readFileSync(filename, "utf8"));
      if (actualDigest !== digest) {
        throw ownershipError(`managed file has user-modified content: ${filename}`, {
          path: filename,
          expectedDigest: digest,
          actualDigest,
        });
      }
    }

    const managedFiles = Object.fromEntries(
      [...desired.entries()].sort(([left], [right]) => left.localeCompare(right, "en")),
    );
    const provider = mcpAppProvider ?? existingProvider;
    const manifestContent = {
      schemaVersion: MANIFEST_SCHEMA_VERSION,
      generator: MANIFEST_GENERATOR,
      agentSkills: skillMode,
      ...(provider
        ? {
            mcpAppProvider: {
              name: provider.identity.name,
              environmentPrefix: provider.identity.environmentPrefix,
              environmentFile: provider.identity.environmentFile,
              contractSource: provider.contractSource,
              contractPath: portableContractPath(root, provider.contractPath),
              bindings: provider.bindings,
              environmentLoading: provider.environmentLoading,
              environmentLoadingMechanism: provider.environmentLoadingMechanism ?? null,
              environmentLoadingEvidencePath: provider.environmentLoadingEvidencePath ?? null,
              ...(provider.providerOrigin
                ? {
                    providerOrigin: provider.providerOrigin,
                    tamaOrigin: provider.tamaOrigin,
                    allowedOrigins: provider.allowedOrigins,
                  }
                : {}),
              ...(provider.localHttps ? { localHttps: provider.localHttps } : {}),
            },
          }
        : {}),
      managedFiles,
    };
    const content = `${JSON.stringify(manifestContent, null, 2)}\n`;
    return operationForContent(manifestPath, content, { allowUnmanagedUpdate: true });
  }

  return { plan, remove, adoptMarkedFile, isManagedFile, manifestOperation };
}
