import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { CORE_REQUIRED_VARIABLES } from "../domain/environment.mjs";
import { ownershipError } from "../errors.mjs";
import { parseEnvironment } from "../shared/environment.mjs";
import { contentDigest, inspectRegularFile } from "../shared/files.mjs";
import { isLoopbackHostname } from "../shared/network.mjs";
import {
  generateOAuthKeyPair,
  validateOAuthPrivateJwk,
  validatePublicJwkSet,
} from "../shared/oauth-key.mjs";
import type { McpAppLocalContract } from "../types.mjs";
import {
  type ComposeDeclarationInspection,
  type ComposeExecute,
  loadComposeServiceEnvironment,
} from "./compose-inspection.mjs";

export const MCP_APP_TAMA_VARIABLES = [
  "TAMA_MCP_APP_MODE",
  "TAMA_MCP_APP_ALLOWED_ORIGINS",
  "TAMA_MCP_APP_AUTHORIZATION_SERVER",
  "TAMA_MCP_APP_JWKS_URI",
  "TAMA_MCP_APP_INTROSPECTION_ENDPOINT",
  "TAMA_MCP_APP_SIGNING_ALGORITHMS",
  "TAMA_MCP_APP_RESOURCE",
  "TAMA_MCP_APP_INTROSPECTION_CLIENT_ID",
  "TAMA_MCP_APP_INTROSPECTION_SIGNING_ALGORITHM",
  "TAMA_MCP_APP_INTROSPECTION_SIGNING_KEY_ID",
  "TAMA_MCP_APP_INTROSPECTION_PRIVATE_KEY",
  "TAMA_MCP_APP_INTROSPECTION_PUBLIC_KEYS",
] as const;
const TAMA_KEY = "TAMA_MCP_APP_INTROSPECTION_PRIVATE_KEY";
const TAMA_KID = "TAMA_MCP_APP_INTROSPECTION_SIGNING_KEY_ID";
const TAMA_OVERLAP = "TAMA_MCP_APP_INTROSPECTION_PUBLIC_KEYS";

export type McpAppRecovery = {
  contract: McpAppLocalContract;
  tamaPath: string;
  providerPath: string;
  providerService?: string;
  tamaPublic: Map<string, string>;
  providerPublic: Map<string, string>;
  sourceDigests: [string, string][];
  issues: string[];
};

/** Render only portable dotenv assignments; values are never interpolated by Compose. */
export function renderRecoveryEnvironment(values: Map<string, string>): string {
  for (const [name, value] of values) {
    if (!/^[A-Z][A-Z0-9_]*$/u.test(name) || /['\r\n\0]/u.test(value))
      throw ownershipError(`the ${name} assignment cannot be emitted safely`);
  }
  return [
    "# Generated by Tama Kit. Keep private; do not commit.",
    ...[...values].map(([name, value]) => `${name}='${value}'`),
    "",
  ].join("\n");
}

/** Secret-free integration examples for future clones; existing examples remain project-owned. */
export function mcpAppRecoveryExample(
  content: string,
  secrets: readonly string[],
  allowedNames: readonly string[],
): string {
  const parsed = parseEnvironment(content, "integration example");
  const values = new Map([...parsed].filter(([name]) => allowedNames.includes(name)));
  for (const name of secrets) if (values.has(name)) values.set(name, "replace-me");
  return renderRecoveryEnvironment(values).replace(
    "Keep private; do not commit.",
    "Public recovery inputs; replace secret placeholders in private files only.",
  );
}

export function topologyRuntimeValues(contract: McpAppLocalContract): Map<string, string> {
  const topology = contract.topology;
  return new Map(
    topology
      ? [
          ["PHX_HOST", topology.tama_host],
          ["TAMA_OAUTH_ISSUER", topology.tama_origin],
          ["TAMA_BASE_URL", topology.tama_origin],
          ["TAMA_MCP_RESOURCE", `${topology.tama_origin}/mcp`],
          ["TAMA_MCP_ALLOWED_ORIGINS", topology.allowed_origins.join(",")],
        ]
      : [],
  );
}

function origin(value: string, name: string): string {
  try {
    const url = new URL(value);
    if (
      !["http:", "https:"].includes(url.protocol) ||
      url.username ||
      url.password ||
      url.pathname !== "/" ||
      url.search ||
      url.hash ||
      /['$\r\n]/u.test(value)
    )
      throw new Error();
    return url.origin;
  } catch {
    throw ownershipError(
      `the current ${name} must be an absolute public origin without credentials, paths or interpolation`,
    );
  }
}

function resourceOrigin(value: string, name: string): string {
  try {
    const url = new URL(value);
    if (url.pathname !== "/mcp/app" || url.search || url.hash) throw new Error();
    return origin(url.origin, name);
  } catch {
    throw ownershipError(`the current ${name} must identify the /mcp/app resource`);
  }
}

function originList(value: string): string {
  const values = value.split(",").map((v) => origin(v.trim(), "allowed origins"));
  if (
    !values.length ||
    values.length > 32 ||
    new Set(values).size !== values.length ||
    values.some((v) => new URL(v).protocol !== "https:" && !isLoopbackHostname(new URL(v).hostname))
  )
    throw ownershipError(
      "current MCP App allowed origins must be unique HTTPS or loopback origins",
    );
  return values.sort().join(",");
}

/** Current public inputs and native env layers, with markers in place of absent private files. */
export function inspectMcpAppRecovery(input: {
  inspection: ComposeDeclarationInspection;
  contract: McpAppLocalContract;
  contractPath: string;
  tamaService: string;
  tamaPath: string;
  corePath: string;
  providerService?: string;
  missingPaths: string[];
  reissuing: boolean;
  execute?: ComposeExecute;
}): McpAppRecovery {
  const { inspection, contract } = input;
  const root = inspection.root;
  const providerPath = resolve(root, contract.provider.environment_file);
  const roles = contract.bindings;
  const result: McpAppRecovery = {
    contract,
    tamaPath: input.tamaPath,
    providerPath,
    tamaPublic: new Map(),
    providerPublic: new Map(),
    issues: [],
    sourceDigests: [],
  };
  const read = (path: string): Map<string, string> => {
    if (!inspectRegularFile(path)) return new Map();
    const content = readFileSync(path, "utf8");
    result.sourceDigests.push([path, contentDigest(content)]);
    return parseEnvironment(content, path);
  };
  const contractContent = readFileSync(input.contractPath, "utf8");
  result.sourceDigests.push([input.contractPath, contentDigest(contractContent)]);
  const tamaExamples = [
    read(`${input.corePath}.example`),
    ...(input.tamaPath === input.corePath ? [] : [read(`${input.tamaPath}.example`)]),
  ];
  const providerExample = read(`${providerPath}.example`);
  const providerPrivate = read(providerPath);
  const tama = loadComposeServiceEnvironment(
    inspection,
    input.tamaService,
    {
      missingPaths: input.missingPaths,
      suppliedVariables: [...CORE_REQUIRED_VARIABLES, ...MCP_APP_TAMA_VARIABLES],
      suppliedVariablesByPath: new Map([
        [
          input.corePath,
          [
            ...CORE_REQUIRED_VARIABLES,
            ...(input.corePath === input.tamaPath ? MCP_APP_TAMA_VARIABLES : []),
          ],
        ],
        [
          input.tamaPath,
          input.corePath === input.tamaPath
            ? [...CORE_REQUIRED_VARIABLES, ...MCP_APP_TAMA_VARIABLES]
            : [...MCP_APP_TAMA_VARIABLES],
        ],
      ]),
    },
    input.execute,
  );
  result.sourceDigests.push(...tama.sourceDigests);
  if (tama.unresolved.length)
    result.issues.push(
      `MCP App environment depends on missing secrets: ${tama.unresolved.join(", ")}`,
    );
  const loaders = Object.entries(inspection.services)
    .filter(
      ([name, service]) =>
        name !== input.tamaService &&
        service.env_file?.some((ref) => resolve(root, ref.path) === providerPath),
    )
    .map(([name]) => name);
  let provider = providerPrivate;
  if (input.providerService && !loaders.includes(input.providerService)) {
    result.issues.push("selected --provider-service does not load the current provider fragment");
  } else if (loaders.length > 1 && !input.providerService) {
    result.issues.push(
      "multiple Compose services load the provider fragment; select --provider-service",
    );
  } else {
    result.providerService = input.providerService ?? loaders[0];
    if (result.providerService) {
      const resolved = loadComposeServiceEnvironment(
        inspection,
        result.providerService,
        { missingPaths: input.missingPaths, suppliedVariables: Object.values(roles) },
        input.execute,
      );
      provider = resolved.values;
      result.sourceDigests.push(...resolved.sourceDigests);
      if (resolved.unresolved.length)
        result.issues.push(
          `provider environment depends on missing secrets: ${resolved.unresolved.join(", ")}`,
        );
    } else if (contract.environment_loading.mechanism === "compose-env-file") {
      result.issues.push(
        "the current contract declares a Compose provider, but no service loads its fragment",
      );
    }
  }
  const missingTama = input.missingPaths.includes(input.tamaPath);
  const missingProvider = input.missingPaths.includes(providerPath);
  if (missingTama && [TAMA_KEY, TAMA_KID].some((name) => tama.values.has(name)))
    result.issues.push(
      "surviving Compose settings shadow missing Tama signing material; restore the missing fragment instead of reissuing it",
    );
  if (
    missingProvider &&
    [roles.access_token_private_signing_key, roles.access_token_signing_key_id].some((name) =>
      provider.has(name),
    )
  )
    result.issues.push(
      "surviving Compose settings shadow missing provider signing material; restore the missing fragment instead of reissuing it",
    );
  if (input.reissuing) {
    if (!missingTama && tama.values.get("TAMA_MCP_APP_MODE") !== "prepared")
      result.issues.push(
        "the surviving Tama MCP App mode must be prepared before new signing material can be issued; existing files are never changed",
      );
    if (!missingProvider && provider.get(roles.mode) !== "prepared")
      result.issues.push(
        "the surviving provider mode must be prepared before new signing material can be issued; existing files are never changed",
      );
    for (const [name, values] of [
      ["Tama", tama.values],
      ["provider", provider],
    ] as const) {
      const modeName = name === "Tama" ? "TAMA_MCP_APP_MODE" : roles.mode;
      if (values.has(modeName) && values.get(modeName) !== "prepared")
        result.issues.push(`effective ${name} mode conflicts with a new prepared fragment`);
    }
  }
  const choose = (
    name: string,
    candidates: (string | undefined)[],
    normalize: (v: string) => string,
  ): string => {
    const present = candidates.filter((v): v is string => v !== undefined);
    if (!present.length) {
      result.issues.push(
        `public MCP App ${name} is missing; provide project-owned integration .example files or restore surviving private files`,
      );
      return "";
    }
    try {
      const values = present.map(normalize);
      if (new Set(values).size !== 1)
        result.issues.push(
          `current MCP App ${name} inputs disagree; repair the examples, contract or effective environment before recovery`,
        );
      return values[0];
    } catch (error) {
      result.issues.push(error instanceof Error ? error.message : "invalid public MCP App inputs");
      return "";
    }
  };
  const providerOrigin = choose(
    "provider origin",
    [
      tama.values.get("TAMA_MCP_APP_AUTHORIZATION_SERVER"),
      ...tamaExamples.map((v) => v.get("TAMA_MCP_APP_AUTHORIZATION_SERVER")),
      provider.get(roles.issuer),
      providerExample.get(roles.issuer),
      contract.topology?.provider_origin,
    ],
    (v) => origin(v, "provider origin"),
  );
  const tamaOrigin = choose(
    "resource",
    [
      tama.values.get("TAMA_MCP_APP_RESOURCE"),
      ...tamaExamples.map((v) => v.get("TAMA_MCP_APP_RESOURCE")),
      provider.get(roles.resource),
      providerExample.get(roles.resource),
      contract.topology?.resource,
    ],
    (v) => resourceOrigin(v, "MCP App resource"),
  );
  const allowed = choose(
    "allowed origins",
    [
      tama.values.get("TAMA_MCP_APP_ALLOWED_ORIGINS"),
      ...tamaExamples.map((v) => v.get("TAMA_MCP_APP_ALLOWED_ORIGINS")),
      contract.topology?.allowed_origins.join(","),
    ],
    originList,
  );
  const runtime = topologyRuntimeValues(contract);
  if (contract.topology && input.tamaPath !== input.corePath) {
    const port =
      tamaExamples[1]?.get("TAMA_PORT") ?? tama.values.get("PORT") ?? tamaExamples[0]?.get("PORT");
    if (!port || !/^\d+$/u.test(port) || Number(port) < 1 || Number(port) > 65535)
      result.issues.push("the current Tama upstream port is missing or invalid");
    else runtime.set("TAMA_PORT", port);
  }
  const resource = `${tamaOrigin}/mcp/app`;
  result.tamaPublic = new Map([
    ["TAMA_MCP_APP_MODE", "prepared"],
    ["TAMA_MCP_APP_ALLOWED_ORIGINS", allowed],
    ["TAMA_MCP_APP_AUTHORIZATION_SERVER", providerOrigin],
    ["TAMA_MCP_APP_JWKS_URI", `${providerOrigin}${contract.public_endpoints.jwks}`],
    [
      "TAMA_MCP_APP_INTROSPECTION_ENDPOINT",
      `${providerOrigin}${contract.public_endpoints.introspection}`,
    ],
    ["TAMA_MCP_APP_SIGNING_ALGORITHMS", "RS256"],
    ["TAMA_MCP_APP_RESOURCE", resource],
    ["TAMA_MCP_APP_INTROSPECTION_CLIENT_ID", `${resource}/introspection`],
    ["TAMA_MCP_APP_INTROSPECTION_SIGNING_ALGORITHM", "RS256"],
    ...(input.tamaPath !== input.corePath ? [...runtime] : []),
  ]);
  result.providerPublic = new Map([
    [roles.mode, "prepared"],
    [roles.issuer, providerOrigin],
    [roles.resource, resource],
    [roles.access_token_signing_algorithm, "RS256"],
    [roles.introspection_client_id, `${resource}/introspection`],
    [roles.introspection_jwks_uri, `${tamaOrigin}${contract.public_endpoints.jwks}`],
  ]);
  for (const [name, expected] of result.tamaPublic) {
    const runtimeOverride = runtime.has(name);
    const candidates =
      runtimeOverride && input.tamaPath !== input.corePath
        ? [...(!missingTama ? [tama.values] : []), ...tamaExamples.slice(1)]
        : [tama.values, ...tamaExamples];
    for (const values of candidates) {
      if (name === "TAMA_MCP_APP_MODE") {
        if (
          !missingTama &&
          values === tama.values &&
          !["disabled", "prepared", "enabled"].includes(values.get(name) ?? "")
        )
          result.issues.push("the effective Tama MCP App mode is missing or invalid");
        continue;
      }
      if (!values.has(name)) {
        if (
          !missingTama &&
          values === tama.values &&
          !(
            contract.topology &&
            ["TAMA_MCP_APP_RESOURCE", "TAMA_MCP_APP_INTROSPECTION_CLIENT_ID"].includes(name)
          )
        )
          result.issues.push(`the effective ${name} is missing`);
        continue;
      }
      if (name === "TAMA_MCP_APP_ALLOWED_ORIGINS") continue; // compared as a set above
      if (values.get(name) !== expected)
        result.issues.push(`current ${name} disagrees with the MCP App public identity`);
    }
  }
  for (const [name, expected] of result.providerPublic) {
    if (name === roles.mode) {
      if (
        !missingProvider &&
        !["disabled", "prepared", "enabled"].includes(provider.get(name) ?? "")
      )
        result.issues.push("the effective provider MCP App mode is missing or invalid");
      continue;
    }
    if (!missingProvider && !provider.has(name))
      result.issues.push(`the effective ${name} is missing`);
    for (const values of [provider, providerExample])
      if (values.has(name) && values.get(name) !== expected)
        result.issues.push(`current ${name} disagrees with the MCP App public identity`);
  }
  if (!missingTama)
    result.issues.push(...mcpSigningIssues(tama.values, TAMA_KEY, TAMA_KID, TAMA_OVERLAP));
  if (!missingProvider)
    result.issues.push(
      ...mcpSigningIssues(
        provider,
        roles.access_token_private_signing_key,
        roles.access_token_signing_key_id,
        roles.access_token_public_overlap_keys,
      ),
    );
  // Preflight serialization without generating any keys, including dry-run.
  renderRecoveryEnvironment(result.tamaPublic);
  renderRecoveryEnvironment(result.providerPublic);
  return result;
}

function mcpSigningIssues(
  values: Map<string, string>,
  key: string,
  kid: string,
  overlap: string,
): string[] {
  try {
    if (!values.get(key) || !values.get(kid)) throw new Error();
    validateOAuthPrivateJwk(values.get(key) ?? "", values.get(kid) ?? "", key, kid);
    validatePublicJwkSet(values.get(overlap) ?? "[]", overlap, values.get(kid));
    return [];
  } catch {
    return [`${key}, ${kid} and ${overlap} must contain valid matching signing material`];
  }
}

/** Materialize independent signing pairs only after public/persistence preflight has passed. */
export function renderMcpAppRecovery(
  recovery: McpAppRecovery,
  missingPaths: string[],
): Map<string, string> {
  if (recovery.issues.length) throw ownershipError("MCP App recovery inputs are incomplete");
  const content = new Map<string, string>();
  if (missingPaths.includes(recovery.tamaPath)) {
    const pair = generateOAuthKeyPair("mcp-app-tama");
    content.set(
      recovery.tamaPath,
      renderRecoveryEnvironment(
        new Map([
          ...recovery.tamaPublic,
          [TAMA_KEY, pair.privateJwk],
          [TAMA_KID, pair.kid],
          [TAMA_OVERLAP, "[]"],
        ]),
      ),
    );
  }
  if (missingPaths.includes(recovery.providerPath)) {
    const pair = generateOAuthKeyPair("mcp-app-provider");
    const roles = recovery.contract.bindings;
    content.set(
      recovery.providerPath,
      renderRecoveryEnvironment(
        new Map([
          ...recovery.providerPublic,
          [roles.access_token_private_signing_key, pair.privateJwk],
          [roles.access_token_signing_key_id, pair.kid],
          [roles.access_token_public_overlap_keys, "[]"],
        ]),
      ),
    );
  }
  return content;
}

/** Check native effective values after creation, including every new secret against what was written. */
export function validateRecoveredMcpApp(
  recovery: McpAppRecovery,
  input: {
    inspection: ComposeDeclarationInspection;
    tamaService: string;
    execute?: ComposeExecute;
    created: Map<string, string>;
  },
): void {
  const tama = loadComposeServiceEnvironment(
    input.inspection,
    input.tamaService,
    { missingPaths: [], suppliedVariables: [] },
    input.execute,
  );
  const provider = recovery.providerService
    ? loadComposeServiceEnvironment(
        input.inspection,
        recovery.providerService,
        { missingPaths: [], suppliedVariables: [] },
        input.execute,
      ).values
    : parseEnvironment(readFileSync(recovery.providerPath, "utf8"), recovery.providerPath);
  for (const [path, expected, actual] of [
    [recovery.tamaPath, recovery.tamaPublic, tama.values],
    [recovery.providerPath, recovery.providerPublic, provider],
  ] as const) {
    const created = input.created.get(path);
    const names = created ? parseEnvironment(created, path) : expected;
    for (const [name, value] of names) {
      if (!created && (name === "TAMA_MCP_APP_MODE" || name === recovery.contract.bindings.mode))
        continue;
      // Older HTTPS fragments derive resource/client-id from TAMA_BASE_URL.
      if (
        !created &&
        !actual.has(name) &&
        ["TAMA_MCP_APP_RESOURCE", "TAMA_MCP_APP_INTROSPECTION_CLIENT_ID"].includes(name) &&
        recovery.contract.topology
      )
        continue;
      if (name === "TAMA_MCP_APP_ALLOWED_ORIGINS" && originList(actual.get(name) ?? "") === value)
        continue;
      if (actual.get(name) !== value)
        throw ownershipError(
          `the recovered effective ${name} is shadowed or inconsistent; all new files were rolled back`,
        );
    }
  }
  const roles = recovery.contract.bindings;
  const issues = [
    ...mcpSigningIssues(tama.values, TAMA_KEY, TAMA_KID, TAMA_OVERLAP),
    ...mcpSigningIssues(
      provider,
      roles.access_token_private_signing_key,
      roles.access_token_signing_key_id,
      roles.access_token_public_overlap_keys,
    ),
  ];
  if (issues.length) throw ownershipError(issues.join("; "));
}
