// @ts-check
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { ownershipError } from "../errors.mjs";
import {
  contentDigest,
  generationOperationForContent,
  inspectRegularFile,
  operationForContent,
} from "../shared/files.mjs";

/** Fresh scaffolding only. Established projects are routed before this planner.
 * @param {string} root @param {string} operationId @param {boolean} [resuming]
 */
export function createOwnedFilePlanner(root, operationId, resuming = false) {
  /** @param {string} filename @param {string} content @param {import("../types.mjs").FileOperationOptions} [options] @returns {import("../types.mjs").FileOperation} */
  function plan(filename, content, options = {}) {
    if (resuming && filename !== join(root, "tama/.tama-kit.json") && inspectRegularFile(filename))
      content = readFileSync(filename, "utf8");
    const operation = generationOperationForContent(filename, content, options);
    if (operation.action === "conflict")
      throw ownershipError(
        "generation destination contains different project-owned content; no files were written",
        { path: filename },
      );
    if (operation.action === "create") return operation;
    return {
      action: "unchanged",
      path: filename,
      owner: "user",
      sensitive: options.sensitive ?? false,
      beforeDigest: contentDigest(content),
      afterDigest: contentDigest(content),
      reason: operation.reason,
    };
  }
  return {
    plan,
    receiptOperation() {
      const content = `${JSON.stringify({ schemaVersion: 2, generator: "Generated by Tama Kit", operation: { id: operationId, kind: "bootstrap" }, progress: { status: "complete" } }, null, 2)}\n`;
      const filename = join(root, "tama/.tama-kit.json");
      return resuming
        ? operationForContent(filename, content, { owner: "user", allowUnmanagedUpdate: true })
        : plan(filename, content);
    },
  };
}
