# Generated by Tama Kit. Versions are a tested local-bootstrap compatibility set.

terraform {
  required_version = "{{TERRAFORM_VERSION}}"

  required_providers {
    tama = {
      source  = "upmaru/tama"
      version = "{{PROVIDER_VERSION}}"
    }
  }
}
