import assert from "node:assert/strict";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { readGenerationEvidence } from "../../cli/bootstrap/generation-receipt.mjs";
import { createOwnedFilePlanner } from "../../cli/bootstrap/owned-files.mjs";
import { normalizeGenerationPath, parseGenerationReceipt } from "../../cli/domain/generation.mjs";
import { contentDigest, generationOperationForContent } from "../../cli/shared/files.mjs";
import { applyGenerationPlan, planGeneration } from "../../cli/workflows/generation.mjs";
import { temporaryDirectory } from "../helpers/temporary.mjs";

const complete = {
  schemaVersion: 2,
  generator: "Generated by Tama Kit",
  operation: { id: "initial-setup", kind: "bootstrap" },
  progress: { status: "complete" },
};
function incomplete(paths) {
  return { ...complete, progress: { status: "incomplete", pendingDestinations: paths } };
}

function plan(root, destinations, extra = {}) {
  return planGeneration({ root, evidence: { kind: "absent" }, destinations, ...extra });
}

test("generation paths normalize Windows separators for portable receipts", () => {
  assert.equal(normalizeGenerationPath("tama\\compose.mcp-app.yaml"), "tama/compose.mcp-app.yaml");
});

test("fresh generation creates project-owned output and preserves identical content and permissions", async () => {
  const root = temporaryDirectory("tama-kit-generation-");
  const file = join(root, "README.md");
  writeFileSync(file, "existing\n", { mode: 0o600 });
  const before = statSync(file);
  const result = plan(root, [
    { path: "README.md", content: "existing\n", mode: 0o644 },
    { path: "tama/versions.tf", content: "terraform {}\n" },
  ]);
  assert.deepEqual(
    result.operations.map(({ action }) => action),
    ["preserve", "create"],
  );
  await applyGenerationPlan(result, () => {});
  assert.equal(statSync(file).mode, before.mode);
  assert.equal(statSync(file).ino, before.ino);
  assert.equal(readFileSync(join(root, "tama/versions.tf"), "utf8"), "terraform {}\n");
});

test("a generated comment never authorizes overwriting and a conflict blocks all destinations", async () => {
  const root = temporaryDirectory("tama-kit-generation-");
  const file = join(root, "README.md");
  const original = "<!-- Generated by Tama Kit -->\nDeveloper instructions\n";
  writeFileSync(file, original);
  const result = plan(root, [
    { path: "first.txt", content: "new\n" },
    { path: "README.md", content: "<!-- Generated by Tama Kit -->\nNew template\n" },
  ]);
  assert.equal(result.status, "conflict");
  await assert.rejects(
    applyGenerationPlan(result, () => assert.fail("must not validate")),
    { category: "ownership", exitCode: 4 },
  );
  assert.equal(existsSync(join(root, "first.txt")), false);
  assert.equal(readFileSync(file, "utf8"), original);
});

test("completed and legacy generation never recreates deleted output or touches customized output", async () => {
  const root = temporaryDirectory("tama-kit-generation-");
  const filename = join(root, "versions.tf");
  writeFileSync(filename, "custom provider version\n");
  const before = statSync(filename);
  for (const evidence of [
    { kind: "legacy", schemaVersion: 1 },
    { kind: "receipt", receipt: complete },
  ]) {
    const result = plan(
      root,
      [
        { path: "versions.tf", content: "old version\n" },
        { path: "deleted.tf", content: "do not recreate\n" },
      ],
      { evidence },
    );
    assert.deepEqual(result, { status: "existing", operations: [] });
    await applyGenerationPlan(result, () => assert.fail("must not validate"));
    assert.equal(existsSync(join(root, "deleted.tf")), false);
    assert.equal(readFileSync(filename, "utf8"), "custom provider version\n");
    assert.equal(statSync(filename).mtimeMs, before.mtimeMs);
  }
});

test("resume needs explicit receipt selection, creates only pending destinations and preserves edits", async () => {
  const root = temporaryDirectory("tama-kit-generation-");
  writeFileSync(join(root, "edited.md"), "developer edit\n");
  const evidence = { kind: "receipt", receipt: incomplete(["edited.md", "pending.md"]) };
  const destinations = [
    { path: "edited.md", content: "template\n" },
    { path: "pending.md", content: "pending\n" },
    { path: "deleted.md", content: "previously completed\n" },
  ];
  assert.equal(plan(root, destinations, { evidence }).status, "resume-required");
  assert.throws(
    () => plan(root, destinations, { evidence, resumeOperationId: "wrong" }),
    /unfinished generation receipt/u,
  );
  assert.throws(
    () => plan(root, destinations, { resumeOperationId: "initial-setup" }),
    /unfinished generation receipt/u,
  );
  const result = plan(root, destinations, { evidence, resumeOperationId: "initial-setup" });
  await applyGenerationPlan(result, () => {});
  assert.equal(readFileSync(join(root, "edited.md"), "utf8"), "developer edit\n");
  assert.equal(readFileSync(join(root, "pending.md"), "utf8"), "pending\n");
  assert.equal(existsSync(join(root, "deleted.md")), false);
});

test("legacy evidence ignores stale hashes and noncanonical topology without rewriting files", () => {
  const root = temporaryDirectory("tama-kit-generation-");
  const filename = join(root, ".tama-kit.json");
  const bytes = JSON.stringify(
    {
      schemaVersion: 1,
      generator: "Generated by Tama Kit",
      managedFiles: { "deleted.tf": contentDigest("old content") },
      mcpAppProvider: { localHttps: { providerUpstream: "renamed-service:8080" } },
    },
    null,
    4,
  );
  writeFileSync(filename, bytes);
  const before = statSync(filename);
  assert.deepEqual(readGenerationEvidence(filename), { kind: "legacy", schemaVersion: 1 });
  assert.equal(readFileSync(filename, "utf8"), bytes);
  assert.equal(statSync(filename).mtimeMs, before.mtimeMs);
  assert.deepEqual(readGenerationEvidence(join(root, "absent.json")), { kind: "absent" });
});

test("receipt parsing rejects malformed metadata, unsafe resume paths and accidental secret fields", () => {
  assert.deepEqual(parseGenerationReceipt(complete), complete);
  for (const path of [
    "../outside",
    "/outside",
    "a/../b",
    "a\\b",
    "C:/x",
    "a//b",
    "a/./b",
    "",
    "a\nsecret",
  ]) {
    assert.throws(() => parseGenerationReceipt(incomplete([path])), { category: "ownership" });
  }
  for (const value of [
    { ...complete, token: "PRIVATE" },
    incomplete([]),
    incomplete(["same", "same"]),
    { ...complete, progress: { status: "complete", pendingDestinations: ["x"] } },
  ])
    assert.throws(() => parseGenerationReceipt(value), { category: "ownership" });
  const root = temporaryDirectory("tama-kit-generation-");
  const filename = join(root, ".tama-kit.json");
  for (const bytes of [
    '{"PRIVATE_SENTINEL":',
    JSON.stringify({ ...complete, schemaVersion: 99 }),
    JSON.stringify({
      schemaVersion: 1,
      generator: complete.generator,
      managedFiles: { "../escape": contentDigest("x") },
    }),
  ]) {
    writeFileSync(filename, bytes);
    assert.throws(
      () => readGenerationEvidence(filename),
      (error) => error.category === "ownership" && !error.message.includes("PRIVATE_SENTINEL"),
    );
    assert.equal(readFileSync(filename, "utf8"), bytes);
  }
});

test("generation rejects unsafe paths, duplicate destinations, and symlinks including dangling links", () => {
  const root = temporaryDirectory("tama-kit-generation-");
  for (const destinations of [
    [{ path: "../escape", content: "x" }],
    [
      { path: "same", content: "x" },
      { path: "same", content: "y" },
    ],
  ]) {
    assert.throws(() => plan(root, destinations), { category: "ownership" });
  }
  symlinkSync(join(root, "absent"), join(root, "dangling"));
  assert.throws(() => generationOperationForContent(join(root, "dangling"), "x"), {
    category: "ownership",
  });
  assert.throws(() => readGenerationEvidence(join(root, "dangling")), { category: "ownership" });
  mkdirSync(join(root, "actual"));
  symlinkSync(join(root, "actual"), join(root, "link"));
  assert.throws(() => generationOperationForContent(join(root, "link/new"), "x"), {
    category: "ownership",
  });
  assert.throws(() => generationOperationForContent(join(root, "actual"), "x"), {
    category: "ownership",
  });
});

test("preserved private fragments keep bytes and permissions without permission repair", async () => {
  const root = temporaryDirectory("tama-kit-generation-");
  const filename = join(root, ".private.env");
  writeFileSync(filename, "secret-placeholder");
  chmodSync(filename, 0o400);
  const result = plan(root, [
    { path: ".private.env", content: "secret-placeholder", sensitive: true, mode: 0o600 },
  ]);
  assert.equal(JSON.stringify(result).includes("secret-placeholder"), false);
  await applyGenerationPlan(result, () => {});
  assert.equal(statSync(filename).mode & 0o777, 0o400);
});

test("resumes reuse validated sensitive output published before receipt progress", () => {
  const root = temporaryDirectory("tama-kit-generation-resume-");
  const filename = join(root, "tama/.tama.env");
  mkdirSync(join(root, "tama"));
  const persisted = "SECRET_KEY_BASE=persisted-secret\n";
  writeFileSync(filename, persisted, { mode: 0o600 });
  const planner = createOwnedFilePlanner(root, "resume-secrets", true);
  const result = planner.plan(filename, "SECRET_KEY_BASE=fresh-secret\n", {
    sensitive: true,
    mode: 0o600,
    validateExisting(content) {
      assert.equal(content, persisted);
    },
  });
  assert.equal(result.action, "unchanged");
  assert.equal(result.beforeDigest, contentDigest(persisted));
  assert.equal(result.afterDigest, contentDigest(persisted));
  assert.equal(readFileSync(filename, "utf8"), persisted);
});
