import assert from "node:assert/strict";
import { generateKeyPairSync } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import test from "node:test";
import { parseEnv } from "node:util";
import { resolveEnvironmentPort } from "../../cli/bootstrap/environment.mjs";
import { readMcpAppProvider } from "../../cli/bootstrap/manifest.mjs";
import { validateMcpAppContract } from "../../cli/bootstrap/mcp-app-contract.mjs";
import { validateMcpAppLocalContract } from "../../cli/bootstrap/mcp-app-local-contract.mjs";
import { createBootstrapPlan } from "../../cli/bootstrap/plan.mjs";
import { CLIError, EXIT_CODES } from "../../cli/errors.mjs";
import { generateOAuthKeyPair } from "../../cli/shared/oauth-key.mjs";
import { applyOperations, applyOperationsTransactionally } from "../../cli/shared/write.mjs";
import {
  memoveeContract,
  PINNED_TAMA_IMAGE,
  planWithMcp,
  preparedFor,
  prepareFor,
  project,
  validContract,
  writeContract,
} from "../helpers/mcp-app.mjs";

test("bootstrap plans a complete MCP App provider integration from a discovered contract", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  const plan = planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract }));
  applyOperations(plan.operations);

  const mcp = plan.mcpApp;
  assert.ok(mcp);
  assert.equal(plan.framework, "generic");
  assert.equal(mcp.lifecycle, "prepared");
  assert.equal(mcp.providerOrigin, "http://host.docker.internal:4000");
  assert.equal(mcp.tamaOrigin, "http://127.0.0.1:4001");
  assert.equal(mcp.resource, "http://127.0.0.1:4001/mcp/app");
  assert.equal(mcp.introspectionClientId, "http://127.0.0.1:4001/mcp/app/introspection");
  assert.deepEqual(mcp.allowedOrigins, ["http://127.0.0.1:3000"]);
  assert.equal(mcp.contractSource, "contract");
  assert.equal(mcp.bindings.source, "contract");
  assert.equal(mcp.environmentLoading, "unverified");
  assert.ok(mcp.providerSigningKeyId.startsWith("mcp-app-provider-"));
  assert.ok(mcp.introspectionSigningKeyId.startsWith("mcp-app-tama-"));

  const fragmentPath = join(root, "tama", ".memovee.integration.env");
  const fragment = readFileSync(fragmentPath, "utf8");
  assert.match(fragment, /^# Generated by Tama Kit/mu);
  assert.equal(statSync(fragmentPath).mode & 0o777, 0o600);
  const fragmentValues = parseEnv(fragment);
  assert.equal(fragmentValues.MEMOVEE_TAMA_MCP_APP_MODE, "prepared");
  assert.equal(fragmentValues.MEMOVEE_OAUTH_ISSUER, "http://host.docker.internal:4000");
  assert.equal(fragmentValues.MEMOVEE_TAMA_MCP_APP_RESOURCE, "http://127.0.0.1:4001/mcp/app");
  assert.equal(fragmentValues.MEMOVEE_OAUTH_SIGNING_ALGORITHM, "RS256");
  assert.equal(fragmentValues.MEMOVEE_OAUTH_SIGNING_KEY_ID, mcp.providerSigningKeyId);
  assert.equal(fragmentValues.MEMOVEE_TAMA_INTROSPECTION_CLIENT_ID, mcp.introspectionClientId);
  assert.equal(
    fragmentValues.MEMOVEE_TAMA_INTROSPECTION_JWKS_URI,
    "http://127.0.0.1:4001/.well-known/jwks.json",
  );

  const providerJwk = JSON.parse(fragmentValues.MEMOVEE_OAUTH_PRIVATE_SIGNING_KEY);
  assert.equal(providerJwk.kty, "RSA");
  assert.equal(providerJwk.kid, mcp.providerSigningKeyId);
  assert.equal(Buffer.from(providerJwk.n, "base64url").length, 384);

  assert.deepEqual(JSON.parse(fragmentValues.MEMOVEE_OAUTH_PUBLIC_SIGNING_KEYS), []);

  const tamaValues = parseEnv(readFileSync(join(root, "tama", ".tama.env"), "utf8"));
  assert.equal(tamaValues.TAMA_MCP_APP_MODE, "prepared");
  assert.equal(tamaValues.TAMA_MCP_APP_RESOURCE, "http://127.0.0.1:4001/mcp/app");
  assert.equal(tamaValues.TAMA_MCP_APP_ALLOWED_ORIGINS, "http://127.0.0.1:3000");
  assert.equal(tamaValues.TAMA_MCP_APP_AUTHORIZATION_SERVER, "http://host.docker.internal:4000");
  assert.equal(
    tamaValues.TAMA_MCP_APP_JWKS_URI,
    "http://host.docker.internal:4000/.well-known/jwks.json",
  );
  assert.equal(
    tamaValues.TAMA_MCP_APP_INTROSPECTION_ENDPOINT,
    "http://host.docker.internal:4000/auth/introspections",
  );
  assert.equal(tamaValues.TAMA_MCP_APP_SIGNING_ALGORITHMS, "RS256");
  assert.equal(tamaValues.TAMA_MCP_APP_INTROSPECTION_CLIENT_ID, mcp.introspectionClientId);
  assert.equal(tamaValues.TAMA_MCP_APP_INTROSPECTION_SIGNING_ALGORITHM, "RS256");
  assert.equal(tamaValues.TAMA_MCP_APP_INTROSPECTION_SIGNING_KEY_ID, mcp.introspectionSigningKeyId);

  const tamaJwk = JSON.parse(tamaValues.TAMA_MCP_APP_INTROSPECTION_PRIVATE_KEY);
  assert.equal(tamaJwk.kty, "RSA");
  assert.equal(tamaJwk.kid, mcp.introspectionSigningKeyId);
  assert.equal(Buffer.from(tamaJwk.n, "base64url").length, 384);
  assert.notEqual(tamaJwk.kid, mcp.providerSigningKeyId);
  assert.deepEqual(JSON.parse(tamaValues.TAMA_MCP_APP_INTROSPECTION_PUBLIC_KEYS), []);

  const gitignore = readFileSync(join(root, "tama", ".gitignore"), "utf8");
  assert.match(gitignore, /^\/\.tama\.env$/mu);
  assert.match(gitignore, /^\/\.memovee\.integration\.env$/mu);
  const manifest = JSON.parse(readFileSync(join(root, "tama", ".tama-kit.json"), "utf8"));
  assert.equal(manifest.mcpAppProvider.name, "memovee");
  assert.equal(manifest.mcpAppProvider.contractSource, "contract");
  assert.equal(manifest.mcpAppProvider.environmentLoading, "unverified");
  assert.equal(manifest.mcpAppProvider.bindings.mode, "MEMOVEE_TAMA_MCP_APP_MODE");
  assert.equal(manifest.mcpAppProvider.providerOrigin, "http://host.docker.internal:4000");
  assert.equal(manifest.mcpAppProvider.tamaOrigin, "http://127.0.0.1:4001");
  assert.deepEqual(manifest.mcpAppProvider.allowedOrigins, ["http://127.0.0.1:3000"]);
  const localContractPath = join(root, "tama", "contracts", "mcp-app-provider-v1.json");
  const localContract = validateMcpAppLocalContract(
    JSON.parse(readFileSync(localContractPath, "utf8")),
  );
  assert.equal(localContract.source.type, "provider-contract");
  assert.equal(
    localContract.source.provider_contract_path,
    "priv/contracts/tama-mcp-app-bootstrap-v1.json",
  );
  assert.match(localContract.source.provider_contract_digest ?? "", /^sha256:[0-9a-f]{64}$/u);
  assert.deepEqual(localContract.provider, {
    name: "memovee",
    environment_prefix: "MEMOVEE",
    environment_file: "tama/.memovee.integration.env",
  });
  assert.equal(localContract.bindings.issuer, "MEMOVEE_OAUTH_ISSUER");
  assert.deepEqual(localContract.environment_loading, {
    status: "unverified",
    mechanism: null,
    evidence_path: null,
  });
  assert.doesNotMatch(readFileSync(localContractPath, "utf8"), /PRIVATE KEY|"d"\s*:/u);
  const example = readFileSync(join(root, "tama", ".tama.env.example"), "utf8");
  assert.match(example, /TAMA_MCP_APP_RESOURCE=http:\/\/127\.0\.0\.1:4001\/mcp\/app/u);
  assert.doesNotMatch(example, /TAMA_MCP_APP_INTROSPECTION_PRIVATE_KEY=/u);
  const generatedReadme = readFileSync(join(root, "tama", "README.md"), "utf8");
  assert.match(generatedReadme, /MCP App provider integration/u);
  const discoveredCompose = readFileSync(join(root, "tama", "compose.yaml"), "utf8");
  assert.match(discoveredCompose, /host\.docker\.internal:host-gateway/u);

  const second = planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract }));
  assert.ok(second.operations.every((operation) => operation.action === "unchanged"));
  assert.equal(readFileSync(fragmentPath, "utf8"), fragment);
});

test("bootstrap activates the MCP App integration when requested", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  applyOperations(
    planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })).operations,
  );

  const activated = planWithMcp(
    root,
    preparedFor(root, { contractPath, contractDocument: contract }),
    { activate: true },
  );
  assert.equal(activated.mcpApp?.lifecycle, "enabled");
  applyOperations(activated.operations);
  const fragment = parseEnv(readFileSync(join(root, "tama", ".memovee.integration.env"), "utf8"));
  assert.equal(fragment.MEMOVEE_TAMA_MCP_APP_MODE, "enabled");
  const tama = parseEnv(readFileSync(join(root, "tama", ".tama.env"), "utf8"));
  assert.equal(tama.TAMA_MCP_APP_MODE, "enabled");
});

test("bootstrap keeps provider endpoints on one shared origin and rejects loopback", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  const plan = planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract }), {
    providerOrigin: "http://host.docker.internal:4000",
  });
  applyOperations(plan.operations);

  const mcp = plan.mcpApp;
  assert.ok(mcp);
  assert.equal(mcp.providerOrigin, "http://host.docker.internal:4000");
  const tama = parseEnv(readFileSync(join(root, "tama", ".tama.env"), "utf8"));
  assert.equal(tama.TAMA_MCP_APP_AUTHORIZATION_SERVER, "http://host.docker.internal:4000");
  assert.equal(
    tama.TAMA_MCP_APP_JWKS_URI,
    "http://host.docker.internal:4000/.well-known/jwks.json",
  );
  assert.equal(
    tama.TAMA_MCP_APP_INTROSPECTION_ENDPOINT,
    "http://host.docker.internal:4000/auth/introspections",
  );
  const compose = readFileSync(join(root, "tama", "compose.yaml"), "utf8");
  assert.match(compose, /host\.docker\.internal:host-gateway/u);

  for (const loopbackOrigin of [
    "http://127.0.0.1:4000",
    "http://127.1.2.3:4000",
    "http://localhost:4000",
    "http://[::1]:4000",
    "http://[::ffff:127.0.0.1]:4000",
  ]) {
    const loopbackRoot = project();
    const loopbackContractPath = writeContract(loopbackRoot);
    const loopbackContract = validContract();
    assert.throws(
      () =>
        planWithMcp(
          loopbackRoot,
          preparedFor(loopbackRoot, {
            contractPath: loopbackContractPath,
            contractDocument: loopbackContract,
          }),
          { providerOrigin: loopbackOrigin },
        ),
      (error) =>
        error instanceof CLIError &&
        error.exitCode === EXIT_CODES.USAGE &&
        /loopback and cannot be reached from the Tama container/u.test(error.message) &&
        /host\.docker\.internal/u.test(error.message),
    );
  }
});

test("bootstrap rejects unspecified provider bind addresses", () => {
  for (const providerOrigin of [
    "http://0.0.0.0:4000",
    "http://[::]:4000",
    "http://[::ffff:0.0.0.0]:4000",
  ]) {
    const root = project();
    const contractPath = writeContract(root);
    const contract = validContract();
    assert.throws(
      () =>
        planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract }), {
          providerOrigin,
        }),
      (error) =>
        error instanceof CLIError &&
        error.exitCode === EXIT_CODES.USAGE &&
        /unspecified address/u.test(error.message) &&
        /cannot be reached from the Tama container/u.test(error.message),
    );
  }
});

test("bootstrap requires a provider origin when no contract declares one", () => {
  const root = project();
  const prepared = preparedFor(root, {
    identity: {
      name: "acme",
      environmentPrefix: "ACME",
      environmentFile: "tama/.acme.integration.env",
      source: "flags",
    },
  });
  assert.throws(
    () => planWithMcp(root, prepared),
    (error) =>
      error instanceof CLIError &&
      error.exitCode === EXIT_CODES.USAGE &&
      /provider origin is required/u.test(error.message),
  );
});

test("bootstrap derives conventional bindings for providers without a contract", () => {
  const root = project();
  const prepared = preparedFor(root, {
    identity: {
      name: "acme",
      environmentPrefix: "ACME",
      environmentFile: "tama/.acme.integration.env",
      source: "flags",
    },
  });
  const plan = planWithMcp(root, prepared, { providerOrigin: "http://host.docker.internal:5000" });
  applyOperations(plan.operations);

  const mcp = plan.mcpApp;
  assert.ok(mcp);
  assert.equal(mcp.contractSource, "conventional");
  assert.equal(mcp.contractPath, null);
  assert.equal(mcp.bindings.source, "conventional");
  assert.equal(mcp.bindings.roles.issuer, "ACME_OAUTH_ISSUER");
  assert.equal(mcp.environmentLoading, "unverified");
  const fragment = parseEnv(readFileSync(join(root, "tama", ".acme.integration.env"), "utf8"));
  assert.equal(fragment.ACME_TAMA_MCP_APP_MODE, "prepared");
  assert.equal(fragment.ACME_OAUTH_ISSUER, "http://host.docker.internal:5000");
  const manifest = JSON.parse(readFileSync(join(root, "tama", ".tama-kit.json"), "utf8"));
  assert.equal(manifest.mcpAppProvider.contractSource, "conventional");
  assert.equal(manifest.mcpAppProvider.contractPath, null);
  const localContract = validateMcpAppLocalContract(
    JSON.parse(readFileSync(join(root, "tama", "contracts", "mcp-app-provider-v1.json"), "utf8")),
  );
  assert.equal(localContract.source.type, "generated");
  assert.equal(localContract.source.provider_contract_path, null);
  assert.equal(localContract.source.provider_contract_digest, null);
  assert.equal(localContract.bindings.issuer, "ACME_OAUTH_ISSUER");
});

test("fresh local HTTPS plans leave provider runtime behavior application-owned", () => {
  const root = project();
  const identity = {
    name: "memovee",
    environmentPrefix: "MEMOVEE",
    environmentFile: "tama/.memovee.integration.env",
    source: "flags",
  };
  const prepared = preparedFor(root, { identity });
  prepared.allowedOrigins = ["https://app.localhost"];

  const first = planWithMcp(root, prepared);
  assert.equal(first.mcpApp?.providerOrigin, "https://app.localhost");
  assert.equal(first.mcpApp?.tamaOrigin, "https://tama.app.localhost");
  applyOperations(first.operations);

  const fragmentPath = join(root, "tama", ".memovee.integration.env");
  const fragment = parseEnv(readFileSync(fragmentPath, "utf8"));
  for (const variable of [
    "MEMOVEE_TAMA_LOCAL_HTTPS_PROXY",
    "MEMOVEE_TAMA_LOCAL_HTTPS_EXTERNAL_ORIGIN",
    "MEMOVEE_TAMA_LOCAL_HTTPS_BIND_IP",
    "MEMOVEE_TAMA_LOCAL_HTTPS_UPSTREAM_PORT",
  ]) {
    assert.equal(Object.hasOwn(fragment, variable), false);
  }

  const tama = parseEnv(readFileSync(join(root, "tama", ".tama.env"), "utf8"));
  assert.equal(tama.PHX_HOST, "tama.app.localhost");
  assert.equal(Object.hasOwn(tama, "TAMA_MCP_APP_RESOURCE"), false);
  assert.equal(Object.hasOwn(tama, "TAMA_MCP_APP_INTROSPECTION_CLIENT_ID"), false);

  const rerunPrepared = preparedFor(root, { identity });
  rerunPrepared.allowedOrigins = ["https://app.localhost"];
  const rerun = planWithMcp(root, rerunPrepared);
  assert.equal(rerun.mcpApp?.tamaOrigin, "https://tama.app.localhost");
  assert.ok(
    rerun.operations.every((operation) => operation.action === "unchanged"),
    JSON.stringify(rerun.operations.map(({ action, path, reason }) => ({ action, path, reason }))),
  );
});

test("local HTTPS migration removes legacy Tama-derived MCP App identities", () => {
  const root = project();
  const legacy = planWithMcp(root, preparedFor(root), {
    providerOrigin: "http://host.docker.internal:4000",
    tamaOrigin: "http://127.0.0.1:4001",
    allowedOrigins: ["http://127.0.0.1:3000"],
  });
  applyOperations(legacy.operations);

  const environmentPath = join(root, "tama", ".tama.env");
  const legacyEnvironment = parseEnv(readFileSync(environmentPath, "utf8"));
  assert.equal(legacyEnvironment.TAMA_MCP_APP_RESOURCE, "http://127.0.0.1:4001/mcp/app");
  assert.equal(
    legacyEnvironment.TAMA_MCP_APP_INTROSPECTION_CLIENT_ID,
    "http://127.0.0.1:4001/mcp/app/introspection",
  );

  const migrated = createBootstrapPlan({
    cwd: root,
    targetPath: root,
    image: PINNED_TAMA_IMAGE,
    mcpApp: {
      requested: true,
      activate: false,
      migrateLocalHttps: true,
      providerOrigin: "http://host.docker.internal:4000",
      tamaOrigin: "http://127.0.0.1:4001",
      allowedOrigins: ["https://app.localhost"],
    },
    mcpAppPrepared: preparedFor(root),
  });

  for (const assertion of [
    { providerOrigin: "http://host.docker.internal:5000" },
    { tamaOrigin: "http://127.0.0.1:5001" },
  ]) {
    assert.throws(
      () =>
        createBootstrapPlan({
          cwd: root,
          targetPath: root,
          image: PINNED_TAMA_IMAGE,
          mcpApp: {
            requested: true,
            activate: false,
            migrateLocalHttps: true,
            providerOrigin: "http://host.docker.internal:4000",
            tamaOrigin: "http://127.0.0.1:4001",
            allowedOrigins: ["https://app.localhost"],
            ...assertion,
          },
          mcpAppPrepared: preparedFor(root),
        }),
      /migration assertion/u,
    );
  }

  const contract = validContract();
  const contractPath = writeContract(root, contract);
  assert.doesNotThrow(() =>
    createBootstrapPlan({
      cwd: root,
      targetPath: root,
      image: PINNED_TAMA_IMAGE,
      mcpApp: {
        requested: true,
        activate: false,
        migrateLocalHttps: true,
        allowedOrigins: ["https://app.localhost"],
      },
      mcpAppPrepared: preparedFor(root, { contractPath, contractDocument: contract }),
    }),
  );
  applyOperations(migrated.operations);

  const environment = parseEnv(readFileSync(environmentPath, "utf8"));
  assert.equal(Object.hasOwn(environment, "TAMA_MCP_APP_RESOURCE"), false);
  assert.equal(Object.hasOwn(environment, "TAMA_MCP_APP_INTROSPECTION_CLIENT_ID"), false);
  assert.equal(environment.PHX_HOST, "tama.app.localhost");
  assert.equal(environment.TAMA_OAUTH_ISSUER, "https://tama.app.localhost");
});

test("ordinary local HTTPS reruns preserve public URLs and the selected Tama image", () => {
  const root = project();
  const selectedImage = "ghcr.io/upmaru/tama:0.13.5-server";
  const prepared = preparedFor(root);
  prepared.allowedOrigins = ["https://app.localhost"];
  const first = createBootstrapPlan({
    cwd: root,
    targetPath: root,
    image: selectedImage,
    mcpApp: { requested: true, activate: false },
    mcpAppPrepared: prepared,
  });
  applyOperations(first.operations);

  const rerun = createBootstrapPlan({ cwd: root, targetPath: root });
  assert.equal(rerun.tamaImage, selectedImage);
  assert.ok(
    rerun.operations.every((operation) => operation.action === "unchanged"),
    JSON.stringify(rerun.operations.map(({ action, path, reason }) => ({ action, path, reason }))),
  );
  const environment = parseEnv(readFileSync(join(root, "tama", ".tama.env"), "utf8"));
  assert.equal(environment.TAMA_OAUTH_ISSUER, "https://tama.app.localhost");
  assert.equal(environment.TAMA_MCP_RESOURCE, "https://tama.app.localhost/mcp");
  assert.equal(environment.TAMA_BASE_URL, "https://tama.app.localhost");
  assert.match(
    readFileSync(join(root, "tama", "tama-local-ca.Dockerfile"), "utf8"),
    new RegExp(`^FROM ${selectedImage.replaceAll(".", "\\.")}$`, "mu"),
  );

  const manifestPath = join(root, "tama", ".tama-kit.json");
  const legacyManifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  delete legacyManifest.mcpAppProvider.tamaImage;
  writeFileSync(manifestPath, `${JSON.stringify(legacyManifest, null, 2)}\n`);
  const upgraded = createBootstrapPlan({ cwd: root, targetPath: root });
  assert.equal(upgraded.tamaImage, selectedImage);
  applyOperations(upgraded.operations);
  const upgradedManifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  assert.equal(upgradedManifest.mcpAppProvider.tamaImage, selectedImage);
});

test("a matching provider contract updates provenance without rotating provider keys", async () => {
  const root = project();
  const firstPrepared = await prepareFor(root, {
    providerName: "acme",
    providerOrigin: "http://host.docker.internal:4000",
  });
  const first = planWithMcp(root, firstPrepared, {
    providerOrigin: "http://host.docker.internal:4000",
  });
  applyOperations(first.operations);
  const fragmentPath = join(root, "tama", ".acme.integration.env");
  const originalFragment = readFileSync(fragmentPath, "utf8");

  const acmeContract = JSON.parse(
    JSON.stringify(memoveeContract()).replaceAll("MEMOVEE", "ACME").replaceAll("memovee", "acme"),
  );
  writeContract(root, acmeContract);
  const prepared = await prepareFor(root, {}, { nonInteractive: true });
  const second = planWithMcp(root, prepared);
  assert.equal(second.mcpApp?.localContract?.source.type, "provider-contract");
  assert.equal(second.mcpApp?.localContractOperation?.action, "update");
  const fragmentOperation = second.operations.find(({ path }) => path === fragmentPath);
  assert.equal(fragmentOperation?.action, "unchanged");
  applyOperations(second.operations);
  assert.equal(readFileSync(fragmentPath, "utf8"), originalFragment);
  assert.equal(
    readMcpAppProvider(join(root, "tama"))?.contractPath,
    "priv/contracts/tama-mcp-app-bootstrap-v1.json",
  );
});

test("bootstrap refuses a user-modified managed local contract", () => {
  const root = project();
  const first = planWithMcp(root, preparedFor(root), {
    providerOrigin: "http://host.docker.internal:5000",
  });
  applyOperations(first.operations);
  const localPath = join(root, "tama", "contracts", "mcp-app-provider-v1.json");
  writeFileSync(
    localPath,
    readFileSync(localPath, "utf8").replace('"scope": "local-development"', '"scope": "edited"'),
  );
  assert.throws(
    () =>
      planWithMcp(root, preparedFor(root), {
        providerOrigin: "http://host.docker.internal:5000",
      }),
    (error) =>
      error instanceof CLIError &&
      error.exitCode === EXIT_CODES.OWNERSHIP &&
      /user-modified content/u.test(error.message),
  );
});

test("a failed managed transaction removes a newly generated local contract", async () => {
  const root = project();
  const plan = planWithMcp(root, preparedFor(root), {
    providerOrigin: "http://host.docker.internal:5000",
  });
  await assert.rejects(
    () =>
      applyOperationsTransactionally(plan.operations, () => {
        throw new Error("forced validation failure");
      }),
    /forced validation failure/u,
  );
  assert.equal(existsSync(join(root, "tama", "contracts", "mcp-app-provider-v1.json")), false);
  assert.equal(existsSync(join(root, "tama", ".acme.integration.env")), false);
  assert.equal(existsSync(join(root, "tama", ".tama.env")), false);
});

test("bootstrap rejects Tama image tags outside the supported contract range", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  assert.throws(
    () =>
      createBootstrapPlan({
        cwd: root,
        targetPath: root,
        image: "ghcr.io/upmaru/tama:0.12.0-server",
        mcpApp: { requested: true, activate: false },
        mcpAppPrepared: preparedFor(root, { contractPath, contractDocument: contract }),
      }),
    (error) =>
      error instanceof CLIError &&
      error.exitCode === EXIT_CODES.USAGE &&
      /outside the supported Tama range/u.test(error.message),
  );
  assert.ok(
    planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })).mcpApp,
  );
});

test("bootstrap enforces a narrower provider Tama version range", () => {
  const root = project();
  const contract = validContract();
  contract.supported_tama_versions = ">= 0.13.3 and < 0.14.0";
  const contractPath = writeContract(root, contract);
  assert.throws(
    () => planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })),
    (error) =>
      error instanceof CLIError &&
      error.exitCode === EXIT_CODES.USAGE &&
      /outside the supported Tama range >= 0\.13\.3 and < 0\.14\.0/u.test(error.message) &&
      /accepted provider contract/u.test(error.message),
  );
});

test("bootstrap rejects an unpinned Tama image for the MCP App integration", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  for (const image of ["ghcr.io/upmaru/tama:latest", "ghcr.io/upmaru/tama"]) {
    assert.throws(
      () =>
        createBootstrapPlan({
          cwd: root,
          targetPath: root,
          image,
          mcpApp: { requested: true, activate: false },
          mcpAppPrepared: preparedFor(root, { contractPath, contractDocument: contract }),
        }),
      (error) =>
        error instanceof CLIError &&
        error.exitCode === EXIT_CODES.USAGE &&
        /requires a pinned Tama image/u.test(error.message) &&
        /unresolvable tag/u.test(error.message),
    );
  }
});

test("bootstrap fails closed when the provider identity or contract bindings drift", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  applyOperations(
    planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })).operations,
  );

  const driftedIdentity = preparedFor(root, {
    contractPath,
    contractDocument: contract,
    identity: {
      name: "other",
      environmentPrefix: "OTHER",
      environmentFile: "tama/.other.integration.env",
      source: "flags",
    },
  });
  assert.throws(
    () => planWithMcp(root, driftedIdentity),
    (error) =>
      error instanceof CLIError &&
      error.exitCode === EXIT_CODES.OWNERSHIP &&
      /does not match the resolved identity/u.test(error.message),
  );

  // Undeclared variables are rejected by the contract validator itself, so a
  // drifted binding that still validates must swap two declared variables.
  const memoveeBindings = memoveeContract().bindings;
  const driftedContract = validateMcpAppContract(
    memoveeContract({
      bindings: {
        ...memoveeBindings,
        issuer: memoveeBindings.resource,
        resource: memoveeBindings.issuer,
      },
    }),
  );
  writeContract(root, driftedContract);
  const driftedBindings = preparedFor(root, {
    contractPath,
    contractDocument: driftedContract,
  });
  assert.throws(
    () => planWithMcp(root, driftedBindings),
    (error) =>
      error instanceof CLIError &&
      error.exitCode === EXIT_CODES.USAGE &&
      /bindings changed/u.test(error.message),
  );
});

test("bootstrap requires the provider fragment key and kid together", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  mkdirSync(join(root, "tama"));
  writeFileSync(
    join(root, "tama", ".memovee.integration.env"),
    "MEMOVEE_OAUTH_SIGNING_KEY_ID=mcp-app-provider-orphan\n",
  );
  assert.throws(
    () => planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })),
    (error) =>
      error instanceof CLIError &&
      error.exitCode === EXIT_CODES.OWNERSHIP &&
      /must define/u.test(error.message),
  );
});

test("bootstrap refuses a user-modified provider fragment", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  applyOperations(
    planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })).operations,
  );
  const fragmentPath = join(root, "tama", ".memovee.integration.env");
  writeFileSync(
    fragmentPath,
    readFileSync(fragmentPath, "utf8").replace(
      "MEMOVEE_TAMA_MCP_APP_MODE=prepared",
      "MEMOVEE_TAMA_MCP_APP_MODE=disabled",
    ),
  );
  assert.throws(
    () => planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })),
    (error) =>
      error instanceof CLIError &&
      error.exitCode === EXIT_CODES.OWNERSHIP &&
      /user-modified content/u.test(error.message),
  );
});

test("bootstrap preserves unrelated provider fragment entries and comments", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  applyOperations(
    planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })).operations,
  );
  const fragmentPath = join(root, "tama", ".memovee.integration.env");
  writeFileSync(
    fragmentPath,
    `${readFileSync(fragmentPath, "utf8")}# Provider-owned setting\nMEMOVEE_OTHER_VALUE=kept\n`,
  );
  const rerun = planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract }));
  const operation = rerun.operations.find(({ path }) => path === fragmentPath);
  assert.equal(operation?.action, "unchanged");
  assert.match(
    operation?.content ?? readFileSync(fragmentPath, "utf8"),
    /MEMOVEE_OTHER_VALUE=kept/u,
  );
});

test("bootstrap explicitly migrates provider identity without rotating trust material", async () => {
  const root = project();
  const originalPrepared = await prepareFor(root, {
    providerName: "acme",
    providerOrigin: "http://host.docker.internal:5000",
  });
  const original = planWithMcp(root, originalPrepared, {
    providerOrigin: "http://host.docker.internal:5000",
  });
  applyOperations(original.operations);
  const oldPath = join(root, "tama", ".acme.integration.env");
  const originalValues = parseEnv(readFileSync(oldPath, "utf8"));

  writeFileSync(oldPath, `${readFileSync(oldPath, "utf8")}# Provider-owned\nACME_OTHER=kept\n`);
  const adopted = planWithMcp(root, await prepareFor(root), {
    providerOrigin: "http://host.docker.internal:5000",
  });
  applyOperations(adopted.operations);
  writeFileSync(join(root, ".envrc"), 'dotenv_load "tama/.beta.integration.env"\n');

  const migratedPrepared = await prepareFor(root, {
    providerName: "beta",
    providerPrefix: "BETA",
    providerOrigin: "http://host.docker.internal:5000",
    migrateProviderIdentity: true,
  });
  const migrated = planWithMcp(root, migratedPrepared, {
    providerOrigin: "http://host.docker.internal:5000",
    migrateProviderIdentity: true,
  });
  assert.ok(
    migrated.operations.some(({ action, path }) => action === "delete" && path === oldPath),
  );
  await assert.rejects(
    () =>
      applyOperationsTransactionally(migrated.operations, () => {
        throw new Error("forced post-write failure");
      }),
    /forced post-write failure/u,
  );
  assert.equal(existsSync(oldPath), true);
  assert.equal(existsSync(join(root, "tama", ".beta.integration.env")), false);
  assert.equal(readMcpAppProvider(join(root, "tama"))?.identity.name, "acme");

  const retry = planWithMcp(root, migratedPrepared, {
    providerOrigin: "http://host.docker.internal:5000",
    migrateProviderIdentity: true,
  });
  applyOperations(retry.operations);

  const newPath = join(root, "tama", ".beta.integration.env");
  assert.equal(existsSync(oldPath), false);
  const migratedValues = parseEnv(readFileSync(newPath, "utf8"));
  assert.equal(
    migratedValues.BETA_OAUTH_PRIVATE_SIGNING_KEY,
    originalValues.ACME_OAUTH_PRIVATE_SIGNING_KEY,
  );
  assert.equal(migratedValues.BETA_OAUTH_SIGNING_KEY_ID, originalValues.ACME_OAUTH_SIGNING_KEY_ID);
  assert.equal(migratedValues.ACME_OTHER, "kept");
  assert.equal(migratedValues.ACME_OAUTH_PRIVATE_SIGNING_KEY, undefined);
  assert.equal(readMcpAppProvider(join(root, "tama"))?.identity.name, "beta");

  const convergedPrepared = await prepareFor(root);
  const converged = planWithMcp(root, convergedPrepared, {
    providerOrigin: "http://host.docker.internal:5000",
  });
  assert.ok(converged.operations.every(({ action }) => action === "unchanged"));
});

test("bootstrap preserves a valid persisted public JWK overlap set byte-for-byte", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  applyOperations(
    planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })).operations,
  );

  const rotated = generateOAuthKeyPair("rotated");
  const rotatedKey = { ...JSON.parse(rotated.publicJwk), kid: "rotated-overlap-key" };

  const fragmentPath = join(root, "tama", ".memovee.integration.env");
  const fragment = readFileSync(fragmentPath, "utf8")
    .split("\n")
    .map((line) =>
      line.startsWith("MEMOVEE_OAUTH_PUBLIC_SIGNING_KEYS=")
        ? `MEMOVEE_OAUTH_PUBLIC_SIGNING_KEYS='${JSON.stringify([rotatedKey])}'`
        : line,
    )
    .join("\n");
  writeFileSync(fragmentPath, fragment);

  const tamaPath = join(root, "tama", ".tama.env");
  const tamaEnv = readFileSync(tamaPath, "utf8")
    .split("\n")
    .map((line) =>
      line.startsWith("TAMA_MCP_APP_INTROSPECTION_PUBLIC_KEYS=")
        ? `TAMA_MCP_APP_INTROSPECTION_PUBLIC_KEYS=${JSON.stringify([rotatedKey])}`
        : line,
    )
    .join("\n");
  writeFileSync(tamaPath, tamaEnv);

  const second = planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract }));
  for (const operation of second.operations) {
    if (operation.path === fragmentPath || operation.path === tamaPath) {
      assert.equal(operation.action, "unchanged", operation.path);
    } else if (operation.action !== "unchanged") {
      assert.match(basename(operation.path), /\.tama-kit\.json$/u);
    }
  }
  assert.equal(readFileSync(fragmentPath, "utf8"), fragment);
  assert.equal(readFileSync(tamaPath, "utf8"), tamaEnv);
  assert.deepEqual(
    JSON.parse(parseEnv(readFileSync(fragmentPath, "utf8")).MEMOVEE_OAUTH_PUBLIC_SIGNING_KEYS),
    [rotatedKey],
  );
  assert.deepEqual(
    JSON.parse(parseEnv(readFileSync(tamaPath, "utf8")).TAMA_MCP_APP_INTROSPECTION_PUBLIC_KEYS),
    [rotatedKey],
  );

  applyOperations(second.operations);
  const third = planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract }));
  assert.ok(third.operations.every((operation) => operation.action === "unchanged"));
  assert.equal(readFileSync(fragmentPath, "utf8"), fragment);
  assert.equal(readFileSync(tamaPath, "utf8"), tamaEnv);
});

test("bootstrap fails closed on an invalid persisted public JWK overlap set", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  applyOperations(
    planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })).operations,
  );

  const fragmentPath = join(root, "tama", ".memovee.integration.env");
  const fragmentLines = readFileSync(fragmentPath, "utf8").split("\n");
  const overlapIndex = fragmentLines.findIndex((line) =>
    line.startsWith("MEMOVEE_OAUTH_PUBLIC_SIGNING_KEYS="),
  );
  fragmentLines[overlapIndex] =
    'MEMOVEE_OAUTH_PUBLIC_SIGNING_KEYS=\'[{"kty":"RSA","n":"AQ","e":"AQ","kid":"bad","d":"AQ"}]\'';
  writeFileSync(fragmentPath, fragmentLines.join("\n"));
  assert.throws(
    () => planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })),
    (error) =>
      error instanceof CLIError &&
      error.exitCode === EXIT_CODES.OWNERSHIP &&
      /MEMOVEE_OAUTH_PUBLIC_SIGNING_KEYS/u.test(error.message),
  );

  const currentValues = parseEnv(readFileSync(fragmentPath, "utf8"));
  const currentPrivateJwk = JSON.parse(currentValues.MEMOVEE_OAUTH_PRIVATE_SIGNING_KEY);
  const duplicateCurrentKey = {
    alg: "RS256",
    kid: currentValues.MEMOVEE_OAUTH_SIGNING_KEY_ID,
    kty: "RSA",
    use: "sig",
    n: currentPrivateJwk.n,
    e: currentPrivateJwk.e,
  };
  fragmentLines[overlapIndex] =
    `MEMOVEE_OAUTH_PUBLIC_SIGNING_KEYS='${JSON.stringify([duplicateCurrentKey])}'`;
  writeFileSync(fragmentPath, fragmentLines.join("\n"));
  assert.throws(
    () => planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })),
    (error) =>
      error instanceof CLIError &&
      error.exitCode === EXIT_CODES.OWNERSHIP &&
      /MEMOVEE_OAUTH_PUBLIC_SIGNING_KEYS/u.test(error.message),
  );

  fragmentLines[overlapIndex] = "MEMOVEE_OAUTH_PUBLIC_SIGNING_KEYS='[]'";
  writeFileSync(fragmentPath, fragmentLines.join("\n"));

  const tamaPath = join(root, "tama", ".tama.env");
  const tamaLines = readFileSync(tamaPath, "utf8").split("\n");
  const tamaIndex = tamaLines.findIndex((line) =>
    line.startsWith("TAMA_MCP_APP_INTROSPECTION_PUBLIC_KEYS="),
  );
  tamaLines[tamaIndex] = 'TAMA_MCP_APP_INTROSPECTION_PUBLIC_KEYS=[{"kty":"EC","kid":"bad"}]';
  writeFileSync(tamaPath, tamaLines.join("\n"));
  assert.throws(
    () => planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })),
    (error) =>
      error instanceof CLIError &&
      error.exitCode === EXIT_CODES.OWNERSHIP &&
      /TAMA_MCP_APP_INTROSPECTION_PUBLIC_KEYS/u.test(error.message),
  );
});

test("bootstrap rejects a weak RSA key persisted in the public overlap set", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  applyOperations(
    planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })).operations,
  );

  // The runtime republishes overlap members as trusted RS256 material, so a
  // factorable 1024-bit key must fail the re-bootstrap exactly like any other
  // invalid persisted set.
  const { publicKey } = generateKeyPairSync("rsa", { modulusLength: 1024 });
  const weak = publicKey.export({ format: "jwk" });
  const weakKey = { .../** @type {Record<string, string>} */ (weak), kid: "weak-overlap-key" };
  const fragmentPath = join(root, "tama", ".memovee.integration.env");
  const fragment = readFileSync(fragmentPath, "utf8")
    .split("\n")
    .map((line) =>
      line.startsWith("MEMOVEE_OAUTH_PUBLIC_SIGNING_KEYS=")
        ? `MEMOVEE_OAUTH_PUBLIC_SIGNING_KEYS='${JSON.stringify([weakKey])}'`
        : line,
    )
    .join("\n");
  writeFileSync(fragmentPath, fragment);

  assert.throws(
    () => planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract })),
    (error) =>
      error instanceof CLIError &&
      error.exitCode === EXIT_CODES.OWNERSHIP &&
      /MEMOVEE_OAUTH_PUBLIC_SIGNING_KEYS/u.test(error.message),
  );
});

test("bootstrap derives MCP App origins from the persisted Tama port", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  const first = createBootstrapPlan({
    cwd: root,
    targetPath: root,
    image: PINNED_TAMA_IMAGE,
    port: 4567,
    mcpApp: {
      requested: true,
      activate: false,
      allowedOrigins: ["http://127.0.0.1:3000"],
    },
    mcpAppPrepared: preparedFor(root, { contractPath, contractDocument: contract }),
  });
  applyOperations(first.operations);
  assert.equal(first.mcpApp?.tamaOrigin, "http://127.0.0.1:4567");
  assert.equal(first.mcpApp?.resource, "http://127.0.0.1:4567/mcp/app");

  const second = planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract }));
  assert.equal(second.port, 4567);
  assert.equal(second.mcpApp?.tamaOrigin, "http://127.0.0.1:4567");
  assert.ok(second.operations.every((operation) => operation.action === "unchanged"));
});

test("MCP App reruns update the port and allowed origins without changing stable contract semantics", () => {
  const root = project();
  const contractPath = writeContract(root);
  const contract = validContract();
  const first = planWithMcp(root, preparedFor(root, { contractPath, contractDocument: contract }));
  applyOperations(first.operations);
  const fragmentPath = join(root, "tama", ".memovee.integration.env");
  const firstFragment = parseEnv(readFileSync(fragmentPath, "utf8"));
  const localPath = join(root, "tama", "contracts", "mcp-app-provider-v1.json");
  const firstLocalContract = readFileSync(localPath, "utf8");

  const second = createBootstrapPlan({
    cwd: root,
    targetPath: root,
    image: PINNED_TAMA_IMAGE,
    port: 4020,
    mcpApp: {
      requested: true,
      activate: false,
      allowedOrigins: ["http://127.0.0.1:3001"],
    },
    mcpAppPrepared: preparedFor(root, { contractPath, contractDocument: contract }),
  });
  assert.equal(second.mcpApp?.tamaOrigin, "http://127.0.0.1:4020");
  assert.deepEqual(second.mcpApp?.allowedOrigins, ["http://127.0.0.1:3001"]);
  assert.equal(second.mcpApp?.localContractOperation?.action, "unchanged");
  applyOperations(second.operations);

  const secondFragment = parseEnv(readFileSync(fragmentPath, "utf8"));
  assert.equal(
    secondFragment.MEMOVEE_OAUTH_PRIVATE_SIGNING_KEY,
    firstFragment.MEMOVEE_OAUTH_PRIVATE_SIGNING_KEY,
  );
  assert.equal(
    secondFragment.MEMOVEE_OAUTH_SIGNING_KEY_ID,
    firstFragment.MEMOVEE_OAUTH_SIGNING_KEY_ID,
  );
  assert.equal(secondFragment.MEMOVEE_TAMA_MCP_APP_RESOURCE, "http://127.0.0.1:4020/mcp/app");
  assert.equal(readFileSync(localPath, "utf8"), firstLocalContract);
  const tama = parseEnv(readFileSync(join(root, "tama", ".tama.env"), "utf8"));
  assert.equal(tama.TAMA_MCP_APP_RESOURCE, "http://127.0.0.1:4020/mcp/app");
  assert.equal(tama.TAMA_MCP_APP_ALLOWED_ORIGINS, "http://127.0.0.1:3001");
});

test("bootstrap preserves exact public origins and never infers allowed origins", () => {
  for (const tamaOrigin of [
    "http://localhost:4001",
    "http://127.0.0.1:4001",
    "http://[::1]:4001",
  ]) {
    const root = project();
    const contract = validContract();
    const plan = planWithMcp(root, preparedFor(root, { contractDocument: contract }), {
      tamaOrigin,
    });
    assert.equal(plan.mcpApp?.tamaOrigin, tamaOrigin);
    assert.equal(plan.mcpApp?.resource, `${tamaOrigin}/mcp/app`);
    assert.deepEqual(plan.mcpApp?.allowedOrigins, ["http://127.0.0.1:3000"]);
    assert.equal(plan.mcpApp?.allowedOrigins.includes(tamaOrigin), false);
  }

  const root = project();
  const contract = validContract();
  const first = planWithMcp(root, preparedFor(root, { contractDocument: contract }), {
    tamaOrigin: "http://127.0.0.1:4001",
  });
  applyOperations(first.operations);
  const persisted = readMcpAppProvider(join(root, "tama"));
  assert.equal(persisted?.providerOrigin, "http://host.docker.internal:4000");
  assert.equal(persisted?.tamaOrigin, "http://127.0.0.1:4001");
  assert.deepEqual(persisted?.allowedOrigins, ["http://127.0.0.1:3000"]);
  assert.throws(
    () =>
      planWithMcp(root, preparedFor(root, { contractDocument: contract }), {
        tamaOrigin: "http://localhost:4001",
      }),
    /origin migration|topology migration/u,
  );
});

test("resolveEnvironmentPort preserves a configured port and fails closed on invalid values", () => {
  const root = project();
  assert.equal(resolveEnvironmentPort(root, undefined), 4000);
  assert.equal(resolveEnvironmentPort(root, 5000), 5000);
  mkdirSync(join(root, "tama"));
  writeFileSync(join(root, "tama", ".tama.env"), "TAMA_PORT=4567\n");
  assert.equal(resolveEnvironmentPort(root, undefined), 4567);
  assert.equal(resolveEnvironmentPort(root, 6000), 6000);
  writeFileSync(join(root, "tama", ".tama.env"), "TAMA_PORT=not-a-port\n");
  assert.throws(
    () => resolveEnvironmentPort(root, undefined),
    (error) => error instanceof CLIError && error.exitCode === EXIT_CODES.OWNERSHIP,
  );
});

test("readMcpAppProvider fails closed on a malformed persisted provider block", () => {
  const root = project();
  const tamaDirectory = join(root, "tama");
  mkdirSync(tamaDirectory, { recursive: true });
  assert.equal(readMcpAppProvider(tamaDirectory), null);
  writeFileSync(
    join(tamaDirectory, ".tama-kit.json"),
    JSON.stringify({
      mcpAppProvider: {
        name: "memovee",
        environmentPrefix: "MEMOVEE",
        environmentFile: "tama/.memovee.integration.env",
        contractSource: "bogus",
        contractPath: null,
        bindings: { mode: "MEMOVEE_TAMA_MCP_APP_MODE" },
        environmentLoading: "verified",
      },
    }),
  );
  assert.throws(
    () => readMcpAppProvider(tamaDirectory),
    (error) =>
      error instanceof CLIError &&
      error.exitCode === EXIT_CODES.OWNERSHIP &&
      /invalid mcpAppProvider/u.test(error.message),
  );
});
