import { ownershipError } from "../errors.mjs";
import type { WriteOperation } from "../types.mjs";

/** History only. No topology, credentials, desired content, or completed-file inventory. */
export type GenerationReceipt = {
  schemaVersion: 2;
  generator: "Generated by Tama Kit";
  operation: { id: string; kind: "bootstrap" | "mcp-app" };
  progress: { status: "complete" } | { status: "incomplete"; pendingDestinations: string[] };
};

export type GenerationEvidence =
  | { kind: "absent" }
  | { kind: "legacy"; schemaVersion: 1 }
  | { kind: "receipt"; receipt: GenerationReceipt };

export type GenerationOperation =
  | (WriteOperation & { action: "create" })
  | {
      action: "preserve" | "conflict";
      path: string;
      sensitive: boolean;
      reason: string;
    };

export type GenerationResult = {
  status: "planned" | "conflict" | "existing" | "resume-required";
  operations: GenerationOperation[];
};

export function mapping(value: unknown): Record<string, unknown> | null {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : null;
}

export function isGenerationPath(value: unknown): value is string {
  return (
    typeof value === "string" &&
    value.length > 0 &&
    !/[\\:]/u.test(value) &&
    [...value].every(
      (character) => character.charCodeAt(0) >= 32 && character.charCodeAt(0) !== 127,
    ) &&
    value.split("/").every((part) => part !== "" && part !== "." && part !== "..")
  );
}

/** Reject unknown fields instead of carrying accidental secrets into a converted receipt. */
export function parseGenerationReceipt(value: unknown): GenerationReceipt {
  const record = mapping(value);
  const operation = mapping(record?.operation);
  const progress = mapping(record?.progress);
  const known = (object: Record<string, unknown>, keys: string[]) =>
    Object.keys(object).every((key) => keys.includes(key));
  if (
    record?.schemaVersion !== 2 ||
    record.generator !== "Generated by Tama Kit" ||
    !known(record, ["schemaVersion", "generator", "operation", "progress"]) ||
    !operation ||
    !known(operation, ["id", "kind"]) ||
    typeof operation.id !== "string" ||
    !/^[a-zA-Z0-9_-]{1,128}$/u.test(operation.id) ||
    (operation.kind !== "bootstrap" && operation.kind !== "mcp-app") ||
    !progress
  ) {
    throw ownershipError("invalid generation receipt; inspect current configuration explicitly");
  }
  let parsedProgress: GenerationReceipt["progress"];
  if (progress.status === "complete" && known(progress, ["status"])) {
    parsedProgress = { status: "complete" };
  } else if (
    progress.status === "incomplete" &&
    known(progress, ["status", "pendingDestinations"]) &&
    Array.isArray(progress.pendingDestinations) &&
    progress.pendingDestinations.length > 0 &&
    progress.pendingDestinations.every(isGenerationPath) &&
    new Set(progress.pendingDestinations).size === progress.pendingDestinations.length
  ) {
    parsedProgress = {
      status: "incomplete",
      pendingDestinations: [...progress.pendingDestinations],
    };
  } else {
    throw ownershipError("invalid generation progress; no resume writes are authorized");
  }
  return {
    schemaVersion: 2,
    generator: "Generated by Tama Kit",
    operation: { id: operation.id, kind: operation.kind as "bootstrap" | "mcp-app" },
    progress: parsedProgress,
  };
}
