// @ts-check

import { randomBytes } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { ownershipError } from "../errors.mjs";
import { isValidVaultKey, token } from "../shared/environment.mjs";
import { operationForContent } from "../shared/files.mjs";

const DEFAULT_POSTGRES_PORT = 55_432;
const DEFAULT_TAMA_PORT = 4_001;
const REQUIRED_VARIABLES = [
  "POSTGRES_USER",
  "POSTGRES_PASSWORD",
  "POSTGRES_HOST",
  "POSTGRES_PORT",
  "POSTGRES_DB",
  "POSTGRES_TEST_USERNAME",
  "POSTGRES_TEST_PASSWORD",
  "POSTGRES_TEST_HOSTNAME",
  "POSTGRES_TEST_PORT",
  "TAMA_MAX_VECTOR_DIMENSIONS",
  "TAMA_TEST_MAX_CASES",
  "PORT",
  "TAMA_VAULT_KEY",
  "TAMA_JWT_SECRET",
  "TAMA_SETUP_TOKEN",
];

/** @param {string} content @param {string} filename */
export function parseDevEnvironment(content, filename) {
  const values = new Map();
  const duplicates = new Set();
  for (const line of content.split(/\r?\n/u)) {
    const match = line.match(/^export\s+([A-Z][A-Z0-9_]*)=(.*)$/u);
    if (!match) {
      continue;
    }
    if (values.has(match[1])) {
      duplicates.add(match[1]);
    }
    values.set(match[1], match[2]);
  }
  if (duplicates.size > 0) {
    const variables = [...duplicates].sort();
    throw ownershipError(`${filename} contains duplicate exports: ${variables.join(", ")}`, {
      path: filename,
      variables,
    });
  }
  return values;
}

/** @param {string | undefined} value @param {string} name @param {string} filename */
function validatePort(value, name, filename) {
  if (!value || !/^\d+$/u.test(value)) {
    throw ownershipError(`${filename} has an invalid ${name}: ${value ?? "missing"}`);
  }
  const port = Number.parseInt(value, 10);
  if (port < 1 || port > 65_535) {
    throw ownershipError(`${filename} has an invalid ${name}: ${value}`);
  }
  return port;
}

/** @param {Map<string, string>} values @param {string} filename */
function validateEnvironment(values, filename) {
  const missing = REQUIRED_VARIABLES.filter((name) => !values.get(name));
  if (missing.length > 0) {
    throw ownershipError(`${filename} must export non-empty variables: ${missing.join(", ")}`, {
      path: filename,
      variables: missing,
    });
  }
  const postgresPort = validatePort(values.get("POSTGRES_PORT"), "POSTGRES_PORT", filename);
  const testPort = validatePort(values.get("POSTGRES_TEST_PORT"), "POSTGRES_TEST_PORT", filename);
  const tamaPort = validatePort(values.get("PORT"), "PORT", filename);
  if (postgresPort !== testPort) {
    throw ownershipError(
      `${filename} must use the Compose PostgreSQL port for both development and tests`,
      { path: filename, variables: ["POSTGRES_PORT", "POSTGRES_TEST_PORT"] },
    );
  }
  if (tamaPort === postgresPort) {
    throw ownershipError(
      `${filename} must use different loopback ports for Tama and Compose PostgreSQL`,
      { path: filename, variables: ["PORT", "POSTGRES_PORT", "POSTGRES_TEST_PORT"] },
    );
  }
  if (
    values.get("POSTGRES_HOST") !== "127.0.0.1" ||
    values.get("POSTGRES_TEST_HOSTNAME") !== "127.0.0.1"
  ) {
    throw ownershipError(`${filename} must connect development and tests to Compose on 127.0.0.1`, {
      path: filename,
      variables: ["POSTGRES_HOST", "POSTGRES_TEST_HOSTNAME"],
    });
  }
  if (values.get("TAMA_MAX_VECTOR_DIMENSIONS") !== "1024") {
    throw ownershipError(`${filename} must export TAMA_MAX_VECTOR_DIMENSIONS=1024`, {
      path: filename,
      variable: "TAMA_MAX_VECTOR_DIMENSIONS",
    });
  }
  const testMaxCases = values.get("TAMA_TEST_MAX_CASES");
  if (!testMaxCases || !/^\d+$/u.test(testMaxCases) || Number.parseInt(testMaxCases, 10) < 1) {
    throw ownershipError(`${filename} must export a positive TAMA_TEST_MAX_CASES`, {
      path: filename,
      variable: "TAMA_TEST_MAX_CASES",
    });
  }
  if (!isValidVaultKey(values.get("TAMA_VAULT_KEY") ?? "")) {
    throw ownershipError(`${filename} contains an invalid TAMA_VAULT_KEY`, {
      path: filename,
      variable: "TAMA_VAULT_KEY",
    });
  }
  return { postgresPort, tamaPort };
}

/** @param {number} postgresPort @param {number} tamaPort */
function newEnvironment(postgresPort, tamaPort) {
  const postgresPassword = token(24);
  return [
    "# Generated by Tama Kit. Keep this file private and do not commit it.",
    "",
    "export POSTGRES_USER=tama",
    `export POSTGRES_PASSWORD=${postgresPassword}`,
    "export POSTGRES_HOST=127.0.0.1",
    `export POSTGRES_PORT=${postgresPort}`,
    "export POSTGRES_DB=tama_dev",
    "",
    "export POSTGRES_TEST_USERNAME=tama",
    `export POSTGRES_TEST_PASSWORD=${postgresPassword}`,
    "export POSTGRES_TEST_HOSTNAME=127.0.0.1",
    `export POSTGRES_TEST_PORT=${postgresPort}`,
    "",
    "export TAMA_MAX_VECTOR_DIMENSIONS=1024",
    "export TAMA_TEST_MAX_CASES=16",
    `export PORT=${tamaPort}`,
    `export TAMA_VAULT_KEY=${randomBytes(32).toString("base64")}`,
    `export TAMA_JWT_SECRET=${token(32)}`,
    `export TAMA_SETUP_TOKEN=${token(24)}`,
    "",
  ].join("\n");
}

/** @param {string} content */
function upgradeGeneratedEnvironment(content) {
  if (!content.startsWith("# Generated by Tama Kit.")) {
    return content;
  }
  const additions = [];
  if (!/^export\s+TAMA_MAX_VECTOR_DIMENSIONS=/mu.test(content)) {
    additions.push("export TAMA_MAX_VECTOR_DIMENSIONS=1024");
  }
  if (!/^export\s+TAMA_TEST_MAX_CASES=/mu.test(content)) {
    additions.push("export TAMA_TEST_MAX_CASES=16");
  }
  return additions.length === 0
    ? content
    : content.replace(/^export\s+PORT=/mu, `${additions.join("\n")}\nexport PORT=`);
}

/** @param {string} content @param {number} postgresPort */
function updatePostgresPort(content, postgresPort) {
  return content.replace(
    /^export\s+(POSTGRES_PORT|POSTGRES_TEST_PORT)=.*$/gmu,
    (_line, name) => `export ${name}=${postgresPort}`,
  );
}

/** @param {string} content @param {number} tamaPort */
function updateTamaPort(content, tamaPort) {
  return content.replace(/^export\s+PORT=.*$/mu, `export PORT=${tamaPort}`);
}

/** @param {Map<string, string>} values */
function postgresEnvironment(values) {
  return [
    "# Generated by Tama Kit from .envrc. Keep this file private.",
    `POSTGRES_USER=${values.get("POSTGRES_USER")}`,
    `POSTGRES_PASSWORD=${values.get("POSTGRES_PASSWORD")}`,
    `POSTGRES_DB=${values.get("POSTGRES_DB")}`,
    "",
  ].join("\n");
}

/**
 * @param {string} root
 * @param {{tamaPort?: number, postgresPort?: number}} [options]
 */
export function planDevEnvironment(root, options = {}) {
  const requestedTamaPort = options.tamaPort;
  const requestedPostgresPort = options.postgresPort;
  const filename = join(root, ".envrc");
  const original = upgradeGeneratedEnvironment(
    existsSync(filename)
      ? readFileSync(filename, "utf8")
      : newEnvironment(
          requestedPostgresPort ?? DEFAULT_POSTGRES_PORT,
          requestedTamaPort ?? DEFAULT_TAMA_PORT,
        ),
  );
  const currentValues = parseDevEnvironment(original, filename);
  const current = validateEnvironment(currentValues, filename);
  const postgresPort = requestedPostgresPort ?? current.postgresPort;
  const tamaPort = requestedTamaPort ?? current.tamaPort;
  const postgresContent =
    postgresPort === current.postgresPort ? original : updatePostgresPort(original, postgresPort);
  const content =
    tamaPort === current.tamaPort ? postgresContent : updateTamaPort(postgresContent, tamaPort);
  const values = parseDevEnvironment(content, filename);
  const effective = validateEnvironment(values, filename);
  return {
    postgresPort: effective.postgresPort,
    tamaPort: effective.tamaPort,
    values,
    operations: [
      operationForContent(filename, content, { sensitive: true, mode: 0o600 }),
      operationForContent(join(root, ".tama.dev.postgres.env"), postgresEnvironment(values), {
        sensitive: true,
        mode: 0o600,
      }),
    ],
  };
}

/** @param {string} root */
export function readDevSetupUrl(root) {
  const filename = join(root, ".envrc");
  const values = parseDevEnvironment(readFileSync(filename, "utf8"), filename);
  const port = values.get("PORT");
  const setupToken = values.get("TAMA_SETUP_TOKEN");
  if (!port || !setupToken) {
    throw ownershipError(`${filename} must export PORT and TAMA_SETUP_TOKEN`);
  }
  return `http://localhost:${port}/setup/root?token=${encodeURIComponent(setupToken)}`;
}
